### ISSUE TITLE
autochdir is conflicting with the harpoon 

### ISSUE THREAD

**Issue by theSafdarAwan** [ThePrimeagen/harpoon#105]
currently i have this settings 
" set autochdir
to make it easier for navigation throught fuzzy finders and the newtrw but i hope the there was a way to tell the harpoon to detect the root directory as the lsp servers do like .git or something like that it should expose and api so we could configure it

**Comment by tg0h** [comment]
@imSafdarAwan, the PR for #73 will fix this
