### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Psych3r** [ThePrimeagen/harpoon#108]
Please add doc/harpoon.txt

**Comment by ThePrimeagen** [comment]
It is something I may or may not do.  I need to get the time first.  If you wish to take a stab at it, great.  I will work with you on a pr :)

**Comment by matu3ba** [comment]
see also #198

**Comment by ferdinandyb** [comment]
You could try generating it from the README: https://github.com/FooSoft/md2vim
