### ISSUE TITLE
Short filenames in menu

### ISSUE THREAD

**Issue by thilofischer** [ThePrimeagen/harpoon#109]
When opening the menu, the marked files are listed with the complete path relative from the cwd.
It would improve readability to only show the filename and as much as needed from the path to remain unique.
This is the same way some buffer line plugins handle this.
See: https://github.com/akinsho/bufferline.nvim#unique-buffer-names

**Comment by asbjornhaland** [comment]
The gui menu is more than just a visual representation of the path. You can also change the path and save it to update the mark.

**Comment by ThePrimeagen** [comment]
it could be a setting.  But its definitely not something I want to deal with, especially with the fact that they can be hand mutated.  This means you will have to have a 2 way transform, doesn't sound fun to me.

**Comment by thilofischer** [comment]
Yeah, I didn't think of that...
