### ISSUE TITLE
Broken UI and functionality

### ISSUE THREAD

**Issue by sQVe** [ThePrimeagen/harpoon#110]
👋🏼 

This plugin looks like something that would fit wonderfully into my workflow but I'm failing to get it to install properly. The UI looks like this:
![image](https://user-images.githubusercontent.com/2284724/139944643-45b63e6c-0060-4af5-bbcb-21806107f7c8.png)

Renaming a line in the popup, like `NEED´, breaks the mark and just opens a new file named `NEED`. When trying this out on a larger project it seemed to get stuck in some weird loop also - ending up feeding the content of the current buffer into the popup instead.

I'm loading the plugin with:

```lua
    use({
        'ThePrimeagen/harpoon',
        event = 'BufEnter',
        requires = {'nvim-lua/plenary.nvim', 'nvim-lua/popup.nvim'},
    })
```

Making it non-lazy makes not difference.

**Comment by ThePrimeagen** [comment]
This is real interesting.

I have literally never seen this, but I could try it out.  There must be some sort of something odd happening here.  Thanks for the issue report :)

**Comment by sQVe** [comment]
By the way, my dotfiles are located here: https://github.com/sQVe/dotfiles. I don't know how to even start debugging this as the issue is so weird.

It's 100% replicateable on my system. I tried running the lastest version of harpoon just now and got the exact same issue.

**Comment by sQVe** [comment]
Solved. Closing.
