### ISSUE TITLE
harpoon/lua/harpoon/ui.lua:36: attempt to call field 'create' (a nil value)

### ISSUE THREAD

**Issue by TamaMcGlinn** [ThePrimeagen/harpoon#111]
I've been using harpoon since yesterday. Today I cd'ed into a project, started up neovim, opened a file and tried to bring up the harpoon UI to see if my main files are still harpooned (I'm expecting them to be), but I got this error:

```
E5108: Error executing lua /home/me/.vim/plugged/harpoon/lua/harpoon/ui.lua:36: attempt to call field 'create' (a nil value)
```

I am on commit 22b2650 which is up to date as of now.

**Comment by TamaMcGlinn** [comment]
It reproduces every time, so as a quick workaround I have switched  back to the previous commit on master. Looks like #106 has caused this.

**Comment by TamaMcGlinn** [comment]
Also, note that I am up-to-date on plenary (commit 96e821e), so I do actually have the commit that moves popup into plenary (5e5c87f).

I've tried a bunch of stuff, like calling popup.popup_create instead, which does exist but doesn't return the needed values. I also tried removing the popup.nvim plugin, which really shouldn't be necessary, as you should rename functions when you move them for compatibility with other plugins which may still need popup.nvim defined as it was. And indeed, that doesn't fix this either.

**Comment by Dotrar** [comment]
Seconded, any prior commit should work fine.
for vim-plug:

```vim
Plug 'ThePrimeagen/harpoon', {'commit' : '54a47d3590936d81c32ba10fc66b39b41ac83f3'}
```

**Comment by TamaMcGlinn** [comment]
This same issue broke telescope today, an unrelated plugin.

**Comment by TamaMcGlinn** [comment]
@Dotrar Could you do: `put =execute('lua print(vim.inspect(vim.api.nvim_list_runtime_paths()))')` (and then you could save as .json and use [`:FormatCode`](https://github.com/google/vim-codefmt) to prettify `js-beautify`). There should only be one install of plenary in that output, but in my case there were two, the latter being outdated; perhaps from earlier usages of other plugin managers that were never cleaned up. In my case, the fix was `rm -rf ~/.local/share/nvim/site/pack` - a bit heavy-handed, but I wanted to make sure this bug dies a fiery death.

**Comment by Dotrar** [comment]
I only have one install of plenary, and I'm using vim-plug as I mentioned. There doesn't really seem to be much else of use in  that output

**Comment by TamaMcGlinn** [comment]
So, you checked that the plenary install listed in the runtime path is up-to-date, e.g. by opening it and doing `git log`, and seeing that the commit '' ? And you verified that there is only one directory in the list ending in 'plenary.nvim', and that none end in 'popup.nvim' ? I can't imagine it being anything else than these.

**Comment by ThePrimeagen** [comment]
jeeze, sorry this happened to y'all.  I can revert that change to fix it all.

**Comment by Dotrar** [comment]
No i don't think plenary is up to date; I'll try updating everything and see how it goes.

**Comment by TamaMcGlinn** [comment]
I don't think any further change is necessary - the error message should always bring users here, and the instructions I gave should make things clear. Also, this should only happen to a very small subset of users, who have something wrong with their plenary install.

Reverting would be another two breaking changes - users need to add and then remove popup.nvim again when you decide to do this update later.

Vim plugins, sadly, do not have proper dependency management, such as you see in e.g. alire, conan, pip, cargo etc. So we will always have such problems, and @ThePrimeagen did the best currently possible by simply delaying the usage of features in a library being used.
