### ISSUE TITLE
Quick Menu Improvements

### ISSUE THREAD

**Issue by atchim** [ThePrimeagen/harpoon#113]
I've been playing around with this plugin since I watched [this masterpiece](https://youtu.be/Qnos8aApa9g) and I'm quite enjoying the workflow that `harpoon` provides to me. During my usage experience, I've been noticed some things that may be improved. Let me list them below.

## `'harpoon.ui'.toggle_quick_menu()`

It's really nice that the user can just edit the quick menu and then press `<Esc>` followed by `q` to exit or even an `<Enter>` to just open the entry of the selected line. However, I don't see the need to have to write the index of the entry before its path. I think the approach used in `'harpoon.cmd-ui'.toggle_quick_menu()` is a lot better. The quick menu for commands previously mentioned relies on the user to move lines around in order to switch the index of the commands in the list. It also has `number` set by default, which I think it's a better way to visualize the index of each entry. That said, I think that the quick menu for the `ui` module would be improved if behaved like the quick menu from `cmd-ui`.

## `'harpoon.cmd-ui'.toggle_quick_menu()`

This quick menu is almost perfect to me, but it lacks some essential features... The first one is that by pressing `<Enter>` in normal mode won't actually run the command in the selected line, which I think is a lot counterintuitive. The second one is that by pressing `q` in normal mode the menu won't close.

Really thanks for this plugin!

**Comment by atchim** [comment]
Hi @rod-stuchi! I actually don't have these maps.

**Comment by rod-stuchi** [comment]
@atchim In my case the "problem" was in my maps, I tested this disabling all my maps, and enabling one by one, until I found the mapping `;` to `:` in normal mode was breaking the harpoon default behavior (`q`, `esc`, `enter` in list)

If anyone knows how to solved this would be great

**Comment by ThePrimeagen** [comment]
I will be supporting this shortly.  Give me a bit and I'll try to get some harpoon streams coming!

I have allowed some tech debt get into the project and making some of these changes can be hard

**Comment by rod-stuchi** [comment]
Thanks @clbrunet  and @ThePrimeagen 

I don't know if solves the problem that @atchim described, for me, it works only if I comment this line.

```lua
local keymap = vim.api.nvim_set_keymap 

keymap('n', ';', ':', { noremap = true })
-- keymap('n', ':', ';', { noremap = true })
```
keeping this map is useful to use with `f` in normal mode

**Comment by ThePrimeagen** [comment]
I assume the fix addresses this issue.  Reopen if it does not :)

**Comment by atchim** [comment]
@ThePrimeagen, it's actually working pretty fine!

**Comment by rod-stuchi** [comment]
Yeah, it's working beautiful after #115 
Thank you @clbrunet and @ThePrimeagen
