### ISSUE TITLE
enter_on_sendcmd does not work

### ISSUE THREAD

**Issue by clbrunet** [ThePrimeagen/harpoon#120]
The setup global setting `enter_on_sendcmd` does not run the command passed to the terminal when calling `sendCommand`.

It work for me when replacing '\n' with '\r' in `sendCommand`. For my computer this diff fixes the issue :
```diff
diff --git a/lua/harpoon/term.lua b/lua/harpoon/term.lua
index fef47ec..ee1f8a5 100644
--- a/lua/harpoon/term.lua
+++ b/lua/harpoon/term.lua
@@ -78,7 +78,7 @@ M.sendCommand = function(idx, cmd, ...)
     end
 
     if global_config.enter_on_sendcmd then
-        cmd = cmd .. "\n"
+        cmd = cmd .. "\r"
     end
 
     if cmd then
```

Am I the only one to encounter this problem ?
And if not, can we apply the diff above or will it not work for every OS ?

**Comment by maxmahlke** [comment]
I can confirm this issue and that the fix suggested by @clbrunet works in my case. I'm using harpoon with tmux, both neovim (0.7-dev) and harpoon are up-to-date.

**Comment by matu3ba** [comment]
This can be platform-specific, so testing on Windows, Mac and Linux would be helpful: https://www.oreilly.com/library/view/mac-os-x/0596004605/ch01s06.html

vim.fs should contain a function to get the platform-specific line ending, but I am not sure about that.

For example, on Linux, I do use `map('n', '<C-s>j', [[<cmd>lua require("harpoon.term").sendCommand(1, vim.fn.getreg('j') .. "\n")<CR>]], opts)`.

**Comment by clbrunet** [comment]
@matu3ba I tried on Windows with a fresh installation of nvim and the enter_on_sendcmd configuration on the Windows command line also only work when replacing the "\n" by a "\r".
Unfortunately I don't have a mac to test this.

**Comment by vid512** [comment]
Why was this (and #157) closed "as completed"? The issue is still present. 

Currently I have to workaround this problem by adding "\r" suffix to commands on windows.
