### ISSUE TITLE
Default mappings suggestion

### ISSUE THREAD

**Issue by gerazov** [ThePrimeagen/harpoon#125]
Awesome talk at [Vimconf 2021](https://www.youtube.com/watch?v=Qnos8aApa9g&list=PLcTu2VkAIIWyuX-yNe0KNSPR7wjS2lNKz&index=1)! :sunglasses: 

It would be helpful to have a set of default/suggested keymappings in the README (another TODO :slightly_smiling_face: : ) that we could tweak/use. They can also be Dvorak :sweat_smile: I was searching through your [dotfiles](https://github.com/ThePrimeagen/.dotfiles/blob/master/nvim/.config/nvim/init.vim) but to no avail.

For instance, if we want to map a key in the lua block, do we do:
```lua
    keybindings = {
      add_file = '<leader>ha',
      toggle_quick_menu = '<leader>ht',
    }
``` 
Or do we need to do
```lua
vim.api.nvim_set_keymap("n", "<leader>hh", require("harpoon.ui").nav_file(1), {})
```
Which doesn't work ...

I finally came up with:
```lua
vim.api.nvim_set_keymap("n", "<leader>;a", ":lua require('harpoon.mark').add_file()<CR>", {})
vim.api.nvim_set_keymap("n", "<leader>;t", ":lua require('harpoon.ui').toggle_quick_menu()<CR>", {})
vim.api.nvim_set_keymap("n", "<leader>;h", ":lua require('harpoon.ui').nav_file(1)<CR>", {})
vim.api.nvim_set_keymap("n", "<leader>;j", ":lua require('harpoon.ui').nav_file(2)<CR>", {})
vim.api.nvim_set_keymap("n", "<leader>;k", ":lua require('harpoon.ui').nav_file(3)<CR>", {})
vim.api.nvim_set_keymap("n", "<leader>;l", ":lua require('harpoon.ui').nav_file(4)<CR>", {})
```
But I'm sure there's a more elegant way to do it ... :sweat_smile:

**Comment by renerocksai** [comment]
Hi, if you're looking for some suggestions, look at [prime's primal harpoon keyboard priming here](https://github.com/ThePrimeagen/.dotfiles/blob/master/nvim/.config/nvim/plugin/harpoon.vim) :grin:

**Comment by gerazov** [comment]
So that's where they were :sweat_smile: thanks!

**Comment by nick-nds** [comment]
@gerazov The above solution is good, but limits you to 4 main files or you need more remaps. I have a different solution which is better for some cases.
`vim.api.nvim_set_keymap('n', '<leader>h', '<cmd>lua require("harpoon.ui").nav_file(vim.v.count1)<cr>',  opts)`
Now, 1<leader>h navigates to file 1 and 3<leader>h navigates to file 3

**Comment by gerazov** [comment]
Good suggestion :+1:
