### ISSUE TITLE
closing file using harpoon

### ISSUE THREAD

**Issue by bryant-the-coder** [ThePrimeagen/harpoon#138]
hey primeagen, is it possible to close a buffer using harpoon? it would be fun if can :))

**Comment by matu3ba** [comment]
Closing buffers is an open problem in neovim. Can you be more explicit, who this would work?
Harpoon was designed for efficient buffer navigation and not keeping track of its usage.

**Comment by bryant-the-coder** [comment]
I mean like i press :q it quits all buffers. But i just wanna close that specific buffer. Is that achievable??
