### ISSUE TITLE
Keybinding for international keyboard layouts.

### ISSUE THREAD

**Issue by OliverAThunes** [ThePrimeagen/harpoon#145]
Using a Norwegian keyboard layout, I wanted to be able to bind my four fingers to quickly jump to the first four files in the quick menu.
But with a Norwegian keyboard, those keys are JKLØ, and Ø does not like to be bound.

This is what my bindings in harpoon.vim file looks like:

```
nnoremap <silent><C-j> :lua require("harpoon.ui").nav_file(1)<CR>
nnoremap <silent><C-k> :lua require("harpoon.ui").nav_file(2)<CR>
nnoremap <silent><C-l> :lua require("harpoon.ui").nav_file(3)<CR>
nnoremap <silent><C-ø> :lua require("harpoon.ui").nav_file(4)<CR>
```

I'm not entirely sure if this is a harpoon issue or neovim issue, but a solution would be grealy appreciated.

**Comment by asbjornhaland** [comment]
I'm also norwegian, but I use US-layout (a custom one). You could use `hjkl` instead of `jklø` - I don't think `ø` is supported for keybindings in nvim.

**Comment by ThePrimeagen** [comment]
@asbjornhaland / @OliverAThunes `C-ø` not because of vim, but because of terminal.  Not all C-<key> pairs work.  A good example is C-, does not work.

I am going to close down this issue, and if it isn't a terminal issue / vim issue then I can try to create a work around, but I am unsure if I can.
