### ISSUE TITLE
how to send sigint to terminal

### ISSUE THREAD

**Issue by CRAG666** [ThePrimeagen/harpoon#162]
I want to send a termination signal to a terminal that is executing some command such as npm or any other, this in order to send another command to the same terminal later, I would like to know how I can do it with the method `lua require("harpoon.tmux").sendCommand`

**Comment by ThePrimeagen** [comment]
My guess is that you could always C-v C-d (eof) and send that as a command to terminal.  That would technically close the terminal down.

**Comment by CRAG666** [comment]
lua require("harpoon.tmux").sendCommand(10, "C-d")?

**Comment by matu3ba** [comment]
C-d or SIGINT is in ascii EOT=4, so it is in lua as string `"\4"` as decimal escaping (up to `\ddd` digits).
