### ISSUE TITLE
set autochdir confuses harpoon menu

### ISSUE THREAD

**Issue by radres** [ThePrimeagen/harpoon#166]
I have `set autochdir` enabled. I have set harpoons both in current directory and one directory below.

If I open current directory like
`nvim .`
then select a file that is in directory below, I see entry directory's harpoon menu. Ok, maybe that's how it works, but no, harpoons dont work anymore. I also cannot add any harpoons.

Am I not supposed to ever get into my project from a directory above? Seems like it completely messes it up?

**Comment by tg0h** [comment]
sounds like you want #73
