### ISSUE TITLE
Improving readability by changing background

### ISSUE THREAD

**Issue by premell** [ThePrimeagen/harpoon#169]
It would be nice to add some styling to make the harpoon list more readable. I think just adding some background color to the selected element would be very helpful. 

For example, look at these examples of harpoon and telescope. Its much easier imo to see where the cursor is in the telescope example

![image](https://user-images.githubusercontent.com/65544203/159124705-1a597110-3291-4610-a193-3d812ded1733.png)
![image](https://user-images.githubusercontent.com/65544203/159124539-41c374e0-597c-47b1-8d4c-f09d2aff1945.png)

**Comment by tg0h** [comment]
You can roll your own by adding an auto command to set up cursorline for the harpoon filetype ＼（＾ ＾）／
```lua
-- lua
vim.cmd [[
autocmd Filetype harpoon setlocal cursorline
]]
```
![Screenshot 2022-04-23 at 12 51 18 - kitty@2x](https://user-images.githubusercontent.com/7954426/164878209-d5d1b47a-5e94-4c34-869a-4b88369a08e6.jpg)

**Comment by premell** [comment]
Thats awesome thank you! This should probably be the default or atleast an option imo
