### ISSUE TITLE
Toggle file doesn't update list, deleted file marked as (empty)

### ISSUE THREAD

**Issue by Mariownyou** [ThePrimeagen/harpoon#174]
When toggle file, list doesn't update itself. 
Example:
1. toggle file (state: added, list[filename])
2. toggle another file (state: added, list[filename, filename2])
3. toggle this file again (state: removed, list[filename, (empty)]

I understand the problem with implementation such feature, my goal is point out this issue

**Comment by ThePrimeagen** [comment]
interesting.  What are the apis you are calling?

**Comment by Mariownyou** [comment]
marks api

**Comment by diegoefe** [comment]
Same here, I added this to my harpoon.lua (follow your video) and got the same error:
```lua
vim.keymap.set("n", "<leader>r", mark.rm_file)
```
I had to manually remove it from .local/share/nvim/harpoon.json
