### ISSUE TITLE
An alternate way of persisting data

### ISSUE THREAD

**Issue by RaafatTurki** [ThePrimeagen/harpoon#177]
#### The Issue

1. Harpoon has to parse `~/.local/share/nvim/harpoon.json` on init which is noticeably slow when there are many directories stored in there.  
2. Also all that data is gobbled up together in one file which makes it hard to isolate (to delete as an example).  
3. Furthermore since that data is stored in such way renaming or moving your project elsewhere results in losing all your marks.  

#### Proposed Solution
After all what harpoon is storing is session related data, and vim already provides a way to make sessions that can store global variables, it even provides events of when to load said global vars.  
I've also heard about this `shada` (shared data) file thing but I'm not sure about its relevancy here.  

If all of the above sounds like pain to implement or unneeded then consider adding 2 simple hooks that get and set the current list of marks and a boolean that disables `harpoon.json` all together so I'd have the freedom to store my marks as I please.

**Comment by matu3ba** [comment]
1. How is behavior synchronized, if I have multiple instances of the same session open?
2. shada files have severe problems, see as example https://github.com/neovim/neovim/issues/9063
3. Agreed. harpoon.json is gobbled together.

As motivational example, I have a pile of empty entries, which looks like auto-generated garbage
```json
"/home/user/.config/nix": {"mark": {"marks": []}, "term": {"cmds": []}},
"/home/user/dev/git/rust": {"mark": {"marks": []}, "term": {"cmds": []}},
"/home/user/.git_template/tmp": {"mark": {"marks": []}, "term": {"cmds": []}},
```

Further, it would be good to provide at least some instructions how to 1. remove non-existing paths, 2. how to rename paths in a scripted way with `mv old new` as minimal example.

**Comment by matu3ba** [comment]
However, I dont think that disabling or moving the config elsewhere will fix the problems. JSON also looks like the right format for relative small unstructured data despite all its flaws.

**Comment by RaafatTurki** [comment]
Hey @matu3ba, I've ended up jumping ship over to [reach.nvim](https://github.com/toppair/reach.nvim) due to the lack of response on this issue.

I will not close this but I don't mind if someone else does.

**Comment by matu3ba** [comment]
https://github.com/stedolan/jq/issues/104 with jq should at least remove the rubbish.

https://stackoverflow.com/questions/56692037/filter-empty-and-or-null-values-with-jq could be used in a repl to detect when harpoon creates empty fields in the config.

Personally I use harpoon mostly for shell stuff and do the rest with session files (`:mks sess` and `nvim -S sess`) and `:b file`, because nvim-cmp is relative fast.
So I wouldn't mind having only a local file and everything else in `/tmp`, if it would be supported by anything from the cmdline.
