### ISSUE TITLE
Harpoon tmux go to terminal (window) does not work if user creates sessions with tmux panes

### ISSUE THREAD

**Issue by tg0h** [ThePrimeagen/harpoon#180]
# Problem

harpoon.tmux.gotoTerminal(2) mostly works. However, it does not find the tmux window if the user has manually created windows and panes

## How to repro
<img width="3196" alt="image" src="https://user-images.githubusercontent.com/7954426/164966839-b3e5da26-be91-4bb1-b24b-c96a5686bf99.png">

## Root Cause
- currently create_terminal runs `tmux new window -P -F #{pane_id}` which is problematic. This returns the pane id created and stores it as a window identifier. This assumes that only 1 pane will be created per window. (so that pane_id and window_id remain the same as windows are created) This assumption breaks down once the user manually creates tmux panes.
- when gotoTerminal(2) runs, it searches for any existing tmux windows with the window identifier (the previously stored pane id) but is unable to find the window because terminal_exists(window_id) searches for the window_id in `tmux list-windows` which contains window ids not pane ids. 

## Solution?

tmux.lua
- create_terminal
  - should return both the tmux window id and pane id
- go_to_terminal
  - has to handle both pane and window+pane identifiers

**Comment by CharlesChiuGit** [comment]
Having the same issue, harpoon seems to dislike tmux panes. 🥲

**Comment by matu3ba** [comment]
> This assumption breaks down once the user manually creates tmux panes.

I dont see any simple way to fix this unless the user stores tthe created pane info somewhere for harpoon to read (slowish).
If neovim would be run as remote instance, one could use custom keybindings to tell neovim with harpoon on some port what to store internally.

Otherwise, harpoon will automatically handle all tmux panes and harpoon cant configure all defaults to guard against that.

**Comment by matu3ba** [comment]
@babygau It would help, if you can point other users to the config, better a simplified version or ideally post it here.

**Comment by joshmkennedy** [comment]
I fixed this by changing the terminal_exists function

```lua
    local window_list, _, _ = utils.get_os_command_output({
        "tmux",
        "list-windows",
        "-F",
        "#{pane_id}", -- gives pane_id
    }, vim.loop.cwd())

    -- This has to be done this way because tmux has-session does not give
    -- updated results
    for _, line in pairs(window_list) do
        -- line will now be `%pane_id`
        local window_info = line 
       
        if string.find(line, string.sub(window_id, 2)) then
            exists = true
        end
    end
```

Is this solution problematic?

**Comment by CharlesChiuGit** [comment]
@joshmkennedy maybe submit a pull request?
