### ISSUE TITLE
mark_branch doesn't work

### ISSUE THREAD

**Issue by joshmedeski** [ThePrimeagen/harpoon#183]
I was using Harpoon with it's default settings, then turned on the `mark_branch` flag. When I switch branches all my marks stay the same.

What should I do to fix this?

**Comment by tg0h** [comment]
![image](https://user-images.githubusercontent.com/7954426/169642237-9d3a935f-299b-406a-bb5c-31ec7620b309.png)

for troubleshooting, have a look at your harpoon.json file 
- what is its mark_branch value say

a nuclear option would be to delete the harpoon.json file and try again ... (this will delete all you existing marks)

**Comment by joshmedeski** [comment]
Thanks, that's exactly what I was looking for. I deleted the `harpoon.json` and the feature is working now!
