### ISSUE TITLE
Possibility to add labels

### ISSUE THREAD

**Issue by sarmong** [ThePrimeagen/harpoon#185]
When you have a lot of files in a project, harpoon helps tremendously, but I still sometimes forget why some file is there.

It would be nice to add a label in front of the filename. it could be separated from the filename by ` - ` E.g.

```
sends onclick event - src/services/analytics.tsx
```

**Comment by TamaMcGlinn** [comment]
Came here to suggest something similar. I would want the harpoon buffer to show which of my keybindings corresponds to each file. Perhaps this can be done with an ftplugin vimscript that adds diagnostics (so, not actually buffer contents?).
