### ISSUE TITLE
Go to tmux terminal not working

### ISSUE THREAD

**Issue by skykosiner** [ThePrimeagen/harpoon#187]
Since the tmux functionally came out I have been able to do `:lua :lua require('harpoon.tmux').gotoTerminal(1)` and go to the first terminal or create the first terminal.

Over the past few weeks I have noticed that has not worked. Whenever I call this even if I have that terminal created, harpoon will try and create another new terminal again.

I have tried to understand how the tmux code works to try and change it my self, but I have not got very far.

If anyone knows what the problem is that would be great!

**Comment by tg0h** [comment]
would it be related to https://github.com/ThePrimeagen/harpoon/issues/180?

the go to terminal feature *mostly works* but might not work if you start creating tmux panes

**Comment by CharlesChiuGit** [comment]
Having the same issue, harpoon seems to dislike tmux panes. 🥲
