### ISSUE TITLE
Harpoon is slow?

### ISSUE THREAD

**Issue by rsynnest** [ThePrimeagen/harpoon#188]
I love this plugin, but it seems to be very slow for me. One might even say it could use some coconut oil!?

EDIT: As a workaround, using telescope sped up the interface a lot for me (~3sec -> 0.2sec)
UPDATE: Even with Telescope, this bug makes Harpoon unusable for me. With 4 or 5 marks, every single buffer becomes slow to open (Ctrl+^ , FZF, anything).

### Details
With 6 marks, it takes about 3 seconds for harpoon to pop up, and another 3 seconds to open a chosen file. Each mark I add increases lag by about 0.5 secs. This happens even when there's only a single project in harpoon.json. I also removed all other plugins to rule out any conflicts. The lag isn't affected by directory size or number of git branches.

Is this just me? Or is this the expected performance? I'd be happy to dive into the code to look for speedups, but wanted to share for now.

My harpoon.json with projects removed:
```
{
  "mark_branch": true,
  "projects": {
  },
  "global_settings": {
    "save_on_toggle": false,
    "mark_branch": true,
    "excluded_filetypes": [
      "harpoon"
    ],
    "enter_on_sendcmd": false,
    "save_on_change": true,
    "tmux_autoclose_windows": false
  }
}
```

**Comment by subatiq** [comment]
Having the same problem since install. Timing is also right, 4 files delay the window pop for around 2 seconds

**Comment by matu3ba** [comment]
This is missing alot context to estimate possible causes for the slowdown.
For starters, can you show the startup time of neovim?
What does your setup look like? Do you use tmux? Do you use WSL1, WSL2, mac, Linux, windows?

How big is your harpoon.json in size? What is the biggest line size? How many projects are inside?

**Comment by ThePrimeagen** [comment]
i am very willing to look at this.  

i know there is just some cruft in the code and all.  But that shouldn't lead to a slow down.

i must know, cat /path/to/harpoon.json | wc -c

**Comment by rsynnest** [comment]
Did some quick testing:

**No Slowness**:
- Arch Linux nvim 0.7.2

**Slowness**:
- MacOS 12.5.1  nvim 0.7.2
- iTerm2 and Terminal, with or without tmux
- nvim startup is 413 ms
- `cat harpoon.json | wc -c` = 566
- slowness is dependent only on the number of marks (about 0.5sec slowdown per mark). UI speed is unaffected by directory size, project count, harpoon.json size, or git branch count. 
- maybe related: on MacOS I'm running in a nix-shell, which basically means $PATH is kinda big (80 entries) and paths are kinda long. Will try to see if I can narrow it down any further later today.

**Comment by joeyschoblaska** [comment]
I also started noticing this, also on an M1 mac. `nav_next()` and `nav_prev()` have a tangible delay.

* NVIM v0.8.0
* macOS 12.6
* iTerm2
* nvim startup: 221 ms

```
cat ~/.local/share/nvim/harpoon.json | wc -c
    1793
```

**Comment by c4syner** [comment]
I'm having this issue as well, navigating harpoon is snappy but opening the harpoon UI has a 2-3 sec delay.
- macOS 12.5
- nvim v0.7.2
- iTerm2 
```
cat ~/.local/share/nvim/harpoon.json | wc -c
     286
```
also having this issue on WSL + nvim

**Comment by rsynnest** [comment]
I noticed that it isn't just the quickmenu that slows down. Adding marks makes ALL buffer switching slower (opening files, Telescope, FZF, etc). This happens on all platforms, not just MacOS, though MacOS is signficantly slower than others during testing. Added an improvement for this in #233 

I also noticed that the harpoon quickmenu is significantly slower than normal buffer switching, so it has its own additional issues on top of buffer switching which I haven't dug into yet.

**Comment by subatiq** [comment]
Just got a weird resolution of this problem on MacOS. 

I have almost the same setup as everyone else here, and the same problem.

- MacOS Ventura (also had it on Monterey)
- nvim 0.8.0
- iTerm2/Terminal/Alacritty

Just tried out the Primeagean's nvim config and it's very fast now.

The version of harpoon is the same. 

The main differences are that previously I used vim-plug to install it and had most of my config in vimscript. Now it's packer and lua respectively.

Maybe it will help with investigation.

**Comment by rsynnest** [comment]
@subatiq I do use vim-plug and a mix of lua+viml, but my guess is you're seeing results of recent performance improvements to the plugin. To confirm you can install a version before the improvements and I bet it'll be slow again:

```
use {
'ThePrimeagen/harpoon',
commit = '00f486e9634406bbfc5bc25528685beb530fb3cf'
}
```

**Comment by subatiq** [comment]
@rsynnest tried that just now, the window still appears instantly. 
I tried updating my previous config after you update a couple of weeks ago, but there was no performance boost for me. I started to think that it is a Mac thing. 
Would be funny if the way vim-plug invokes plugins makes it slower on MacOS. For me LSP is also much faster now

**Comment by fceruti** [comment]
I was also experiencing slowness until i removed `null-ls`.

Setup: Neovim 9 , intel, macos ventura 13.3.1

**Comment by rsynnest** [comment]
I should have closed this a while ago my bad, resolved in https://github.com/ThePrimeagen/harpoon/pull/233
Thanks for the input everyone!
