### ISSUE TITLE
Multiple quick menus

### ISSUE THREAD

**Issue by TheLazyTurtle** [ThePrimeagen/harpoon#189]
I have the problem where I have a big project with a front and back-end and I sometimes have a handful of files for the front and back-end I need to work on. The problem I encounter is that I sometimes have 4/5 files for the front and 4/5 for the back. I thought it would be very helpful to be able to have multiple separate harpoon lists / menus.
Keybinds would  look something like this:
`keymap("n", "<leader>ma", ":lua require('harpoon.mark').add_file(1)<cr>", opts)`
`keymap("n", "<leader>mb", ":lua require('harpoon.mark').add_file(2)<cr>", opts)`

`keymap("n", "<leader>qma", ":lua require('harpoon.ui').toggle_quick_menu(1)<cr>", opts)`
`keymap("n", "<leader>qmb", ":lua require('harpoon.ui').toggle_quick_menu(2)<cr>", opts)`

**Comment by matu3ba** [comment]
> I thought it would be very helpful to be able to have multiple separate harpoon lists / menus.

This sounds to me being simpler by exposing all internal state to the user to "build the tables on your own" rather than changing the `tables` into `tables of tables` (or lists) upstream.
