### ISSUE TITLE
[FR] Send command to Tmux from Harpoon menu

### ISSUE THREAD

**Issue by bangedorrunt** [ThePrimeagen/harpoon#202]
At the moment, press Enter on Harpoon menu only send command to the integrated terminal. Because Harpoon also support Tmux, I'd like to have a option to send the command to a default Tmux specific pane, just like we can do with `sendCommand`

**Comment by matu3ba** [comment]
> I'd like to have a option to send the command to a default Tmux specific pane

Here is an example for advanced scripting in tmux I used for some complex IPC testing stuff at work for the log output:
https://github.com/matu3ba/dotfiles/blob/ab31028b93816aa4032a2e2dc45eb3be2c6e9463/templates/tmux#L26

You can send to any tmux pane by its id or the name you have given it based on the session you have defined,
so there is no reason for harpoon to define all combinations if any shell can send it to any tmux pane anyway.

Here is the best tmux guide I know of:
https://gist.github.com/sdondley/b01cc5bb1169c8c83401e438a652b84e

**Comment by matu3ba** [comment]
Note, that tmux needs veery smol timeouts between commands, so if you buffer commands things may break.
