### ISSUE TITLE
harpoon/lua/harpoon/init.lua:13: attempt to call field 'nvim_create_augroup' (a nil value)

### ISSUE THREAD

**Issue by DanMargera** [ThePrimeagen/harpoon#204]
This issue is caused by using a NeoVim version older than 0.7.0 (Ubuntu LTS is on 0.6.1 currently iirc)
I'm not sure what is the minimum required version of nvim for Harpoon.

**Comment by franciscod** [comment]
Also hit this on 0.5.0. I know it's old, but on the README there's a 0.5 badge so I was confused for a while.

**Comment by javierdebug** [comment]
@DanMargera Why did you close this issue? I'm having the same error in 0.6.1. The solution is to update to >0.7?

**Comment by DanMargera** [comment]
Yes, I've opened and closed this issue, just so people could find the fix in google quickly.
I'll edit my original post to make it clearer.

**Comment by javierdebug** [comment]
Thank you, altought I updated the nvim version but the error remains. Should I delete previous installation before installing the newer one?
My version: NVIM v0.9.0-dev-71-gd9a80b8e2
