### ISSUE TITLE
How to remove or reorder harpoon marks?

### ISSUE THREAD

**Issue by johnmathews** [ThePrimeagen/harpoon#205]
Apologies if this is written somewhere, I couldn't find it.

How do you remove a mark once you've added it?
Is it possible to reorganize the marks in the harpoon menu?

Thanks!

**Comment by johnmathews** [comment]
oh wow! its just a buffer `dd` etc works... that's great.
Thanks for your help.

**Comment by ThePrimeagen** [comment]
its actually my favorite part of harpoon is the editable menu.   i use it constantly for reordering.

sometimes visual editors >>>>>>  keycombos

**Comment by tqwewe** [comment]
sad that these kind of features aren't available when using telescope integration with harpoon :(
