### ISSUE TITLE
[FR] Bufferline-like UI for marks

### ISSUE THREAD

**Issue by xiaochuanyu** [ThePrimeagen/harpoon#206]
Say I marked a few files:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1718745/189376451-9eec63dd-c6bf-465b-a795-eb9edb599b14.png">
It would be nice I could just see all the files all the time similar to [bufferline](https://github.com/akinsho/bufferline.nvim).
<img width="521" alt="image" src="https://user-images.githubusercontent.com/1718745/189376229-fa836fa3-699c-419e-aff2-8a8fcd06fcd8.png">

I looked into how to integrate with bufferline a bit but I'm not sure how to query whether given buffer is marked via harpoon.

**Comment by josephsdavid** [comment]
Yeah so this solution is ok (I am daveyjones01!), but it queries too often and it is a bit hacky and slow, I think the write way to do it would be to A) emit an event on `DirChanged` and B) emit an event when you actually do the marking, and then instead query an event buffer (aka a table) to see if it has a change in the harpoon thing and updating the numbers (I think the way tabline framework works is it just runs things on a timer). I am slowly working out a way to handle this, if this is suitable for a PR I am happy to make one!!

**Comment by josephsdavid** [comment]
For your own personal usage, the way i think i am going to handle it is make a little event emitting function (no idea if it works fully i havent tested it):

```lua
local subscriptions = {}
local function notify(message, f, ...)
    if type(f) == "function" then
        local ret = f(...)
        subscriptions[message] = ret
        return ret
    end
    subscriptions[message] = f
end

local function take(message)
    local ret = subscriptions[message]
    subscriptions[message] = nil
    return ret
end

local function notifier(message, f)
    return function(...)
        notify(message, f, ...)
    end
end

return {
    Subscriptions = subscriptions,
    Notify = notify,
    Take = take,
    Notifier = notifier
}
```

and then i can do something like:

```lua
-- somewhere,
E = require("core.events")
vim.api.nvim_create_autocmd({ "DirChanged"}, {
    pattern = "*",
    callback = E.Notifier("harpoonchanged", true),
})
```
and when i keybind i can do something like:

```lua
function harpoon_mark_magic()
    require("harpoon.mark").add_file()
    E.Notify("harpoonchanged", true)
end
```

And then i can just query the my harpoon subscriptions and only run the discord message code when `E.take == true`, saving probably a lot of useless calls

**Comment by josephsdavid** [comment]
update it again almost works, only problem is i cannot get it to update after modifying the quick menu. Links to code for interested parties:

[silly event thing](https://github.com/josephsdavid/neovim2/blob/master/lua/core/events.lua)
[keybind function](https://github.com/josephsdavid/neovim2/blob/319ef57e507eeac12dd9a9eaec15ba672cf6ae12/lua/config/keybinds.lua#L5)
[autocmd(https://github.com/josephsdavid/neovim2/blob/319ef57e507eeac12dd9a9eaec15ba672cf6ae12/lua/config/autocmds.lua#L1)
[tabline](https://github.com/josephsdavid/neovim2/blob/319ef57e507eeac12dd9a9eaec15ba672cf6ae12/lua/config/lines.lua#L53)

**Comment by phortonssf** [comment]
@josephsdavid Were you able to solve this?  Interested in the status and how it turned out. thank you.

**Comment by josephsdavid** [comment]
> @josephsdavid Were you able to solve this? Interested in the status and how it turned out. thank you.

Yeah more or less, i havent really spent enough time to get the quick menu thing fixed, but that is not really a big issue because if i change a buffer or anything like that everything seems to work, I think when i get some time if i make it use plenary it would be perfect, but for now passing messages around to a little table seems to work more or less for me :)

**Comment by Cih2001** [comment]
Hey, I created something simple for myself using tabline framework that may be of your interest.
```lua
-- put this in a lua file like bufferline.lua and require in your init.lua

local function get_marks()
	local h = require("harpoon")
	local config = h.get_mark_config()
	return config.marks
end

local function normalize_path(item)
	local Path = require("plenary.path")
	return Path:new(item):make_relative(vim.loop.cwd())
end

local colors = {
	black = "#000000",
	white = "#ffffff",
	bg = "#181A1F",
	bg_sel = "#282c34",
	temp = "#287c34",
	fg = "#696969",
}

local function make_row(text, opts)
	local row = { text }
	for k, v in pairs(opts) do
		row[k] = v
	end
	return row
end

local function create_pane(f, filename, opts)
	f.set_fg(colors.fg)
	f.add({ "", fg = colors.black, bg = colors.bg_sel })
	if filename then
		f.add(make_row(f.icon(filename) .. " ", opts))
		f.add(make_row(vim.fn.fnamemodify(filename, ":t"), opts))
	end
	f.add({ "", bg = colors.bg_sel, fg = colors.black })
end

local render = function(f)
	f.add({ "  Radioactive ", fg = "#bb0000" })

	local items = get_marks()
	local found = false
	local current_file = normalize_path(vim.api.nvim_buf_get_name(0))
	for _, item in ipairs(items) do
		local selected = current_file == item.filename
		if not found and selected then
			found = true
		end
		local fg = selected and f.icon_color(item.filename) or nil
		create_pane(f, item.filename, { fg = fg, bg = colors.bg_sel })
	end

	if not found then
		create_pane(f, current_file, { fg = colors.temp, bg = colors.bg_sel, gui = "italic" })
	end

	f.add_spacer()

	f.make_tabs(function(info)
		f.add({ "", fg = colors.black, bg = colors.bg_sel })
		f.add({ " " .. info.index .. " ", fg = info.current and colors.white or nil })
		f.add({ "", bg = colors.bg_sel, fg = colors.black })
	end)
end

require("tabline_framework").setup({
	render = render,
	hl = { fg = "#abb2bf", bg = "#181A1F" },
	hl_sel = { fg = "#abb2bf", bg = "#282c34" },
	hl_fill = { fg = "#ffffff", bg = "#000000" },
})

```
