### ISSUE TITLE
Settings per project?

### ISSUE THREAD

**Issue by sorliem** [ThePrimeagen/harpoon#214]
Apologies if this has been answered, I tried my best searching through previous issues.

I'd like to have project specific settings that override the `global_settings` table, is that possible already? 

For example, I'd love to be able to disable `mark_branch` for certain projects:
```lua
require("harpoon").setup({
    global_settings = {
        mark_branch = true
    },
    project_settings = {
        ["$HOME/gitroot/coolrepo"] = {
            mark_branch = false
        }
    }
})
```

**Comment by sorliem** [comment]
If this functionality doesn't exist, I may try and take a crack at it.

**Comment by opalmay** [comment]
This shouldn't be handled by Harpoon. There's are ways of doing this in neovim itself.

**Comment by sorliem** [comment]
I have this workaround currently, but i'm not convinced it's working properly,
```lua
if not string.find(vim.loop.cwd(), "mydir") then
    -- only turn on global mark_branch=true if not in a specific dir
    require("harpoon").setup({
        global_settings = {
            mark_branch = true
        }
    })
end
```
Is there a way you'd recommend?

**Comment by opalmay** [comment]
> I have this workaround currently, but i'm not convinced it's working properly,
> 
> ```lua
> if not string.find(vim.loop.cwd(), "mydir") then
>     -- only turn on global mark_branch=true if not in a specific dir
>     require("harpoon").setup({
>         global_settings = {
>             mark_branch = true
>         }
>     })
> end
> ```
> 
> Is there a way you'd recommend?

Yes, something along these lines should work, assuming the default is false and setup is not needed when using the defaults.

Another idea would be to create a config file in project directories and have neovim look for them on launch. It should be built in and some plugins that enhance it are available

**Comment by sorliem** [comment]
> Another idea would be to create a config file in project directories and have neovim look for them on launch

Oh interesting, did not think of that. I'll look at that too, thanks for the idea @opalmay!

Closing.
