### ISSUE TITLE
gotoTerminal with pane ID doesn't work with Tmux windows

### ISSUE THREAD

**Issue by williamhCode** [ThePrimeagen/harpoon#230]
If I create a new window and get the pane id from $TMUX_PANE, doing `lua require("harpoon.tmux").gotoTerminal("%pane_id")` doesn't work. If goto a pane instead, it works.

The problem is right now, harpoon navigates to a pane using `tmux select-pane -t pane_id`. The problem is that `tmux select-pane -t pane_id` makes the pane active in its own window, but does not change the window. If you do `tmux select-window -t pane_id`, tmux switches to the window that the pane is in. 

I suggest always calling "select-window", so tmux will switch windows even if the pane_id is in another window.
https://github.com/ThePrimeagen/harpoon/blob/4dfe94e633945c14ad0f03044f601b8e6a99c708/lua/harpoon/tmux.lua#L124
New gotoTerminal suggestion:
```lua
function M.gotoTerminal(idx)
    log.trace("tmux: gotoTerminal(): Window:", idx)
    local window_handle = find_terminal(idx)

    if window_handle.pane then
        local _, ret, stderr = utils.get_os_command_output({
            "tmux",
            "select-pane",
            "-t",
            window_handle.window_id,
        }, vim.loop.cwd())

        if ret ~= 0 then
            error("Failed to go to terminal." .. stderr[1])
        end
    end

    local _, ret, stderr = utils.get_os_command_output({
        "tmux",
        "select-window",
        "-t",
        window_handle.window_id,
    }, vim.loop.cwd())

    if ret ~= 0 then
        error("Failed to go to terminal." .. stderr[1])
    end
end

```

**Comment by daltondiaz** [comment]
I have a similar issue, but I think its better create a new function called `function gotoWindow(idx)`. I'll try to do feat related.

**Comment by daltondiaz** [comment]
This issue can be closed because ThePrimeagen say it will not be a problem more in Harpoon 2!
