### ISSUE TITLE
user config is duplicating projects with expanded paths

### ISSUE THREAD

**Issue by polarmutex** [ThePrimeagen/harpoon#25]
it you have defined a project in your harpoon config like "~/path/project" . The user config contains a duplicated entries of the following "~/path/project" and "<path-to-homedir>/path/project"

**Comment by ThePrimeagen** [comment]
ohh sno!  I'll have to take a look at this on sunday

**Comment by ThePrimeagen** [comment]
I didn't take a look at this on sunday, but its obviously something that needs to get fixed.  Will when I have a personal moment.

**Comment by ThePrimeagen** [comment]
I believe this has been taken care of with an earlier PR.  @polarmutex let me know if I should re-open this

**Comment by polarmutex** [comment]
I am still seeing it on my system, pretty sure I am running the latest. I will investigate and see if I can find the issue

**Comment by polarmutex** [comment]
basically the harpoon.json will contain the expanded and non expanded paths for any projects in he config sent to the setup function. this change will invalidate the old non expanded path in the config
