### ISSUE TITLE
Harpoon quick menu launches with too wide of contents

### ISSUE THREAD

**Issue by wassimk** [ThePrimeagen/harpoon#256]
This is how the `require('harpoon.ui').toggle_quick_menu()` menu shows up for me.

![image](https://user-images.githubusercontent.com/2261839/220456984-6715b4b9-82d0-4b8a-834c-a332374d5f49.png)

My installation is barebones, with just some keymaps. You can customize the menu dimensions, but it breaks as I move window sizes around. Would you happen to have any ideas on where I can look to fix this?

**Comment by catgoose** [comment]
If you are using focus.nvim, I used to have this problem: https://github.com/beauwilliams/focus.nvim/issues/64

Not sure what I did to fix it, but it's not a problem for me any more.  Try disabling plugins until you find what is causing this.

**Comment by wassimk** [comment]
Thanks so much, @catgoose! focus.nvim is the conflicting plugin.

**Comment by wassimk** [comment]
For anyone who might see this in the future. Here is how I fixed it for me:

``` lua
vim.keymap.set('n', '<C-e>', function()
  require('focus').focus_disable()
  require('harpoon.ui').toggle_quick_menu()
  require('focus').focus_enable()
end, opts('toggle UI'))
```

**Comment by ThePrimeagen** [comment]
very clever @wassimk
