### ISSUE TITLE
Creating shortcuts in VimL

### ISSUE THREAD

**Issue by p-mackay** [ThePrimeagen/harpoon#273]
For example it is quite straight forward to create a shortcut for Telescope in VimL. How can I create an equivalent command with harpoon example: `nnoremap <leader>ff <cmd>Telescope find_files<cr>`. I want to write shortcuts for harpoon like `nnoremap <leader>a <cmd>harpoon mark<cr>` to mark a file then `Ctrl+e` to view the current files. But I haven't been able to find any documentation on this. Any pointers would be appreciated.

**Comment by asbjornhaland** [comment]
Could you try:

```
nnoremap <leader>a :lua require("harpoon.mark").add_file()<CR>
nnoremap <C-e> :lua require("harpoon.ui").toggle_quick_menu()<CR>
```

I'm currently on mobile so I didn't have a chance to test it myself.
