### ISSUE TITLE
Unmarking files in harpoon

### ISSUE THREAD

**Issue by TheShiningBoots** [ThePrimeagen/harpoon#278]
I had a project which I deleted, but have now created another project with the same name in the same directory however for some reason harpoon thinks the files exist and upon bringing up the harpoon UI shows it to me, how do I remove these file?

**Comment by pockata** [comment]
The harpoon quick menu is just an ordinary buffer so you could use `dd` to delete the current line, or `ggdG` to delete the contents of the entire buffer.

**Comment by TheShiningBoots** [comment]
I am sorry for the late reply but since it worked, i will be closing the issue. Thanks @pockata

**Comment by sativ01** [comment]
@pockata is there a way to delete it in telescope?

**Comment by pockata** [comment]
@sativ01 I don't use a telescope integration with Harpoon so I have no idea.
