### ISSUE TITLE
[Feature request] Truncate long path names

### ISSUE THREAD

**Issue by HendrikPetertje** [ThePrimeagen/harpoon#282]
Heya, thanks for this amazing plugin!

While working on React projects (or even Elixir phoenix projects with context folder structure or other older code-bases) I often find myself in a world where folder structure looks a bit like this:

```
src/components/pages/projects/context/SomeSubContextComponent.tsx
src/components/pages/projects/context/SomeSubContextComponent.module.scss
src/components/pages/projects/context/__tests__/SomeSubContextComponent.test.tsx
```

in harpoon's little UI I can only see the first 50-or-so characters. would it be possible (to add optional user configuration)  to truncate the start of the path if the character length for a path exceeds a certain length? Seeing the file-name is more important than the path that comes before it in most cases (unless generic file names are used perhaps). 

(I'll see if I have some time later this week or next week if i can mod the UI bit a bit myself, it might be a fun excersise)

**Comment by zatlite** [comment]
I do this as a workaround.
After launching the quick menu, go to end of line. 
It's not great when you have a really long path in line 1 and a very short path in other lines because those short paths won't be showing up until you move around.

```lua
          require("harpoon.ui").toggle_quick_menu()
          vim.cmd.norm("$ze")
```

**Comment by AnthonyParkssonos** [comment]
same, our codebase has long path names and i'd like to use harpoon with path truncation

**Comment by ujkan** [comment]
I've devised a temporary hack for this. Check out this [commit](https://github.com/ujkan/harpoon/commit/1c9383b98e3ce17966e99427479a62b0fa1515a3) in my fork.

<img width="560" alt="image" src="https://github.com/ThePrimeagen/harpoon/assets/9451191/dd0d488c-8581-403e-89b1-cb1dee4aa259">

Caveats:
- doesn't work with spaces in file names (should be fixed soon, keep your eyes on the dev branch).
- only tested with marks functionality, it could be the case that some of the changes break something else

**Comment by ujkan** [comment]
I implemented truncation in the [feature/truncate](https://github.com/ujkan/harpoon/tree/feature/truncate) branch of my fork. See below. I will try to open a PR in the next few days.

<img width="562" alt="image" src="https://github.com/ThePrimeagen/harpoon/assets/9451191/4a75cb7d-aaca-4ede-aace-7c09dc52308b">
