### ISSUE TITLE
Navigate with numbers inside the harpoon menu

### ISSUE THREAD

**Issue by AlexXi19** [ThePrimeagen/harpoon#283]
Is it possible to bring up the harpoon menu ui and navigate to the file by entering the number?

**Comment by otavioschwanck** [comment]
it would be awesome to have.

**Comment by asbjornhaland** [comment]
I think you could do something like

`autocmd FileType harpoon nnoremap <buffer><silent> 1 :lua require('harpoon.ui').nav_file(1)<CR>`

I'm currently on mobile, so I didn't have a chance to test it myself.

**Comment by pafael** [comment]
just `:n` with n the line index and <CR> twice is also really fast to type
