### ISSUE TITLE
Enter buffer with <space>

### ISSUE THREAD

**Issue by smartinellimarco** [ThePrimeagen/harpoon#286]
Is it possible to open a buffer from the quick menu using the space key instead of cr?
I hadn't been able to create a keybind that only affects the harpoon buffer.
Thanks in advance for the answers!

**Comment by asbjornhaland** [comment]
I think you could do something like `autocmd FileType harpoon nnoremap <buffer><silent> <space> :lua require('harpoon.ui').select_menu_item()<CR>`

**Comment by smartinellimarco** [comment]
Worked like a charm, thanks!
