### ISSUE TITLE
[bug] nav_next/nav_prev not working when index has gaps

### ISSUE THREAD

**Issue by vitarb** [ThePrimeagen/harpoon#288]
If you add multiple buffers and then remove some buffers in the middle from harpoon, then you can end up with index that has gaps (notice numbers 1,4,5):
![Screenshot from 2023-05-15 17-03-55](https://github.com/ThePrimeagen/harpoon/assets/1311694/8c2edabd-c777-4da4-a42b-7a70f5c76945)
Current logic for 'nav_next`:
```
function M.nav_next()
    log.trace("nav_next()")
    local current_index = Marked.get_current_index()
    local number_of_items = Marked.get_length()

    if current_index == nil then
        current_index = 1
    else
        current_index = current_index + 1
    end

    if current_index > number_of_items then
        current_index = 1
    end
    M.nav_file(current_index)
end
```
Would not be able to handle this scenario gracefully, and will be stuck at the buffer 1, similarly `nav_prev` would be stuck at the buffer 4.

One way to fix this would be adding a loop instead of doing a single check, alternatively we could shift positions of existing buffers whenever file is removed from harpoon list.

**Comment by asbjornhaland** [comment]
I believe this has been discussed before. First of all, I do not like shifting positions whenever a file is removed. The problem is if you are not on a marked file, we don't know which index to get the next from. This is why you get stuck at 1.
But if you are on a marked file, then yes, it would make sense to go to the next valid index (4 in your example).

**Comment by vitarb** [comment]
Would it be possible to store last visited mark and then iterate from that position to the maximum mark id (in case of next)? Then iteration behavior would be the same no matter if you have pre-gap mark open or if you are not on the unmarked buffer, which I think is a great, because you would simply cycle through all marks.
