### ISSUE TITLE
Can't create terminal buffer

### ISSUE THREAD

**Issue by brandoncc** [ThePrimeagen/harpoon#29]
When I execute:

```
:lua require("harpoon.term").gotoTerminal(1)
```

I am shown the following error:

```
E5108: Error executing lua /Users/brandoncc/dev/harpoon/lua/harpoon/term.lua:48: Invalid buffer id: 2
```

Each subsequent time I execute the same command, it says a subsequent buffer id (3, 4, 5, 6, etc).

**Comment by brandoncc** [comment]
I narrowed it down to this line:

```
vim.api.nvim_set_current_buf(current_id)
```

For some reason, it loses the terminal buffer when switching back to the previous buffer. If I edit two files, the file buffers don't stay open either when switching (according to `:buffers`)..so this is either a setting I have to find in my config or a new neovim thing.

**Comment by ThePrimeagen** [comment]
interesting.  Do you have `set hidden`?

**Comment by brandoncc** [comment]
Not that I can find anywhere, but I did find:

```
setlocal buftype=nofile bufhidden=wipe nobuflisted nolist noswapfile nowrap cursorline modifiable nospell
```

in autoload/plug.vim (`vim-plug`). I'm not sure if that is interfering. My config is available [here](https://github.com/brandoncc/nvim).

**Comment by ThePrimeagen** [comment]
this is likely the problem.  set hidden will allow for buffers to remain hidden in an unsaved state.  I guess we could try to add that to the terminal buffer itself upon creation.

**Comment by brandoncc** [comment]
I'm wondering why you don't have the file in your repo. You use the same plugin manager I do. The only difference is where we store our plugins. I changed the storage location to be the same as yours but the same error with harpoon. `:buffers` does seem to reflect the correct buffer list now though.

**Comment by brandoncc** [comment]
I misunderstood, I thought you were saying I _shouldn't_ have `hidden` set. I see now that I need it set. PR opened.
