### ISSUE TITLE
[Feature Request] Toggle marks

### ISSUE THREAD

**Issue by sockthedev** [ThePrimeagen/harpoon#291]
I've been loving the tabline addition. It's really speeding up my harpoon interaction.

I'd love the ability to toggle marks. i.e. quick add/remove a mark. 

Imagining something like the below existing within the docs;

### Toggling Marks

you can toggle marks against a file;
```lua
:lua require("harpoon.mark").toggle_file()
```

--

> P.S. Marry me Prime 💜

**Comment by LintaoAmons** [comment]
Can we also have the icon when toggle marks?

<img width="567" alt="image" src="https://github.com/ThePrimeagen/harpoon/assets/95092244/01180de8-cb72-4f28-97ad-9a628af9027f">

**Comment by kkpagaev** [comment]
I toggle current buffer with "M" and it is already builtin

```lua
local mark = require('harpoon.mark')
local i = mark.get_current_index()
mark.toggle_file(i)
```

For indication if current file is "harpooned", I wrote custom winbar from scratch
![image](https://github.com/ThePrimeagen/harpoon/assets/47981925/61519baf-45ab-4445-af23-0e490f501bb9)

Feel free to take a look on my config in kkpagaev/nvim.conf, code for winbar is located in lua/markbar/winbar in case you interested
