### ISSUE TITLE
[Bug] Tabline doesn't highlight kebab case filenames

### ISSUE THREAD

**Issue by sockthedev** [ThePrimeagen/harpoon#292]
When I have a file with a `-` character, e.g. `foo-bar.ts`, the tabline fails to highlight the current selected file.

**Comment by otavioschwanck** [comment]
This  PR fixes: https://github.com/ThePrimeagen/harpoon/pull/290

Just need to ask @ThePrimeagen to merge it XD

**Comment by otavioschwanck** [comment]
Fixed, can you close this PR?
