### ISSUE TITLE
Support Lazy Vim

### ISSUE THREAD

**Issue by sp71** [ThePrimeagen/harpoon#302]
Lazy Vim is a popular package manager. Would love to have harpoon onboarded to ease integration for users

**Comment by arnold-c** [comment]
Not sure if you mean:
1) instructions for setting up with LazyVim, or
2) asking to have it integrated into LV

but if you're referring to 1) I have something that I think will work for me (bear in mind that I've only just tried harpoon in the last 5 minutes, and I'm pretty new to neovim, so it's very likely there's a better way).

`.config/nvim/lua/plugins/harpoon.lua`

```
return { "ThePrimeagen/harpoon" }
```

`.config/nvim/lua/config/keymaps.lua`

```
...

wk.register({
...
    h = {
        name = "harpoon",
        a = { "<cmd>lua require('harpoon.mark').add_file()<cr>", "add file" },
        r = { "<cmd>lua require('harpoon.mark').rm_file()<cr>", "remove file" },
        m = { "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>", "harpoon menu" },
        n = { "<cmd>lua require('harpoon.ui').nav_next()<cr>", "next file" },
        p = { "<cmd>lua require('harpoon.ui').nav_prev()<cr>", "previous file" },
        ["1"] = { "<cmd> lua require('harpoon.ui').nav_file(1)<cr>", "file 1" },
        ["2"] = { "<cmd> lua require('harpoon.ui').nav_file(2)<cr>", "file 2" },
        ["3"] = { "<cmd> lua require('harpoon.ui').nav_file(3)<cr>", "file 3" },
    },
    H = {
        name = "help/debug/conceal",
        c = {
            name = "conceal",
            h = { ":set conceallevel=1<cr>", "hide/conceal" },
            s = { ":set conceallevel=0<cr>", "show/unconceal" },
        },
        t = {
            name = "treesitter",
            t = { vim.treesitter.inspect_tree, "show tree" },
            c = { ":=vim.treesitter.get_captures_at_cursor()<cr>", "show capture" },
            n = { ":=vim.treesitter.get_node():type()<cr>", "show node" },
        },
    },

...
})

...
```

**Comment by sp71** [comment]
Yes instructions was my goal. There are instructions for packer in the readme so having a lazyvim instruction guide in readme would be greatly appreciated

**Comment by AlexErrant** [comment]
For noobs like me, `wk` is https://github.com/folke/which-key.nvim

**Comment by pineapplegiant** [comment]
I just migrated from `Packer` to `Lazy.nvim` plugin manager today and saw this issue–figured I'd drop my config.

Could probably be tweaked, but this is my cute lil lazynvim config that should work for this:

```lua
return {
	"ThePrimeagen/harpoon",
	lazy = false,
	dependencies = {
		"nvim-lua/plenary.nvim",
	},
	config = true,
	keys = {
		{ "<leader>hm", "<cmd>lua require('harpoon.mark').add_file()<cr>", desc = "Mark file with harpoon" },
		{ "<leader>hn", "<cmd>lua require('harpoon.ui').nav_next()<cr>", desc = "Go to next harpoon mark" },
		{ "<leader>hp", "<cmd>lua require('harpoon.ui').nav_prev()<cr>", desc = "Go to previous harpoon mark" },
		{ "<leader>ha", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>", desc = "Show harpoon marks" },
	},
}

```

**Comment by adelowo** [comment]
Thanks @pineapplegiant!!

**Comment by sharyar** [comment]
For folks who are trying to make this work with Telescope, here is my config: 

```lua
return {
  -- Harpoon plugin configuration
  {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    lazy = false,
    requires = { "nvim-lua/plenary.nvim" }, -- if harpoon requires this
    config = function()
      require("harpoon").setup({})

      local function toggle_telescope_with_harpoon(harpoon_files)
        local file_paths = {}
        for _, item in ipairs(harpoon_files.items) do
          table.insert(file_paths, item.value)
        end

        require("telescope.pickers")
          .new({}, {
            prompt_title = "Harpoon",
            finder = require("telescope.finders").new_table({
              results = file_paths,
            }),
            previewer = require("telescope.config").values.file_previewer({}),
            sorter = require("telescope.config").values.generic_sorter({}),
          })
          :find()
      end
      vim.keymap.set("n", "<leader>a", function()
        local harpoon = require("harpoon")
        toggle_telescope_with_harpoon(harpoon:list())
      end, { desc = "Open harpoon window" })
    end,
    keys = {
      {
        "<leader>A",
        function()
          require("harpoon"):list():append()
        end,
        desc = "harpoon file",
      },
      {
        "<C-b>",
        function()
          local harpoon = require("harpoon")
          harpoon.ui:toggle_quick_menu(harpoon:list())
        end,
        desc = "harpoon quick menu",
      },
      {
        "<leader>1",
        function()
          require("harpoon"):list():select(1)
        end,
        desc = "harpoon to file 1",
      },
      {
        "<leader>2",
        function()
          require("harpoon"):list():select(2)
        end,
        desc = "harpoon to file 2",
      },
      {
        "<leader>3",
        function()
          require("harpoon"):list():select(3)
        end,
        desc = "harpoon to file 3",
      },
    },
  },
}

```

**Comment by ThePrimeagen** [comment]
I just don't know how to integrate this into harpoon.

Appreciate your telescope config, and I'd like to make this a bit easier for others. But at the exact same time I'm not really sure how to make a good telescope harpoon plugin.

**Comment by pineapplegiant** [comment]
Most plugins have some sort of installation instructions in the readme for popular plugin managers like Packer and Lazy. Having it in the readme would be nice, but runs the risk of it getting stale if the plugin manager updates. 


> I just don't know how to integrate this into harpoon.

I do think the telescope integration bit is outside the scope of this issue at the very least, but I'm not sure either. It would be nice to have a harpoon picker in telescope, but maybe that should be a telescope plugin or another plugin altogether idk.

**Comment by cmdecker95** [comment]
> I just migrated from `Packer` to `Lazy.nvim` plugin manager today and saw this issue–figured I'd drop my config.
> 
> Could probably be tweaked, but this should work for this:
> 
> ```lua
> return {
> 	"ThePrimeagen/harpoon",
> 	lazy = false,
> 	dependencies = {
> 		"nvim-lua/plenary.nvim",
> 	},
> 	config = true,
> 	keys = {
> 		{ "<leader>hm", "<cmd>lua require('harpoon.mark').add_file()<cr>", desc = "Mark file with harpoon" },
> 		{ "<leader>hn", "<cmd>lua require('harpoon.ui').nav_next()<cr>", desc = "Go to next harpoon mark" },
> 		{ "<leader>hp", "<cmd>lua require('harpoon.ui').nav_prev()<cr>", desc = "Go to previous harpoon mark" },
> 		{ "<leader>ha", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>", desc = "Show harpoon marks" },
> 	},
> }
> ```

Thank you for this!

I might add that **if you are here because you installed harpoon via LazyVim's `LazyExtras` feature**, then you should delete that version. Then allow this harpoon config to install harpoon from the repo.

If you're still get issues using harpoon (like I did), then go to `~/.local/share/nvim/harpoon` and `rm -rf` that sucker. Removing the harpoon `LazyExtra` should clear that, but if not, the residual artifacts from *that* version of harpoon will screw up running the harpoon commands.

After that, should be good to go!

**Comment by gh0stsrc** [comment]
This also worked for with with telescope

```lua
return {
  {
    "ThePrimeagen/harpoon",
    config = function()
      -- load harpoon as a telescope extension 
      require("telescope").load_extension('harpoon')
      require("harpoon").setup({
        global_settings = {
          -- set marks specific to each git branch inside git repository
          mark_branch = true
        }
      })
    end,
    keys = {
      {
        "hx",
        function()
          require("harpoon.mark").add_file()
        end,
        mode = "n",
        desc = "Harpoon file",
      },
      {
        "hr",
        function()
          require("harpoon.mark").rm_file()
        end,
        mode = "n",
        desc = "Remove harpoon from file",
      },
      {
        "hn",
        function()
          require("harpoon.ui").nav_next()
        end,
        mode = "n",
        desc = "Navigate to the next harpooned file",
      },
      {
        "hp",
        function()
          require("harpoon.ui").nav_prev()
        end,
        mode = "n",
        desc = "Navigate to the previous harpooned file",
      },
      {
        "hm",
        "<cmd>Telescope harpoon marks<cr>",
        mode = "n",
        desc = "Show harpoons",
      }
    },
  },
}
```
