### ISSUE TITLE
add hotkey that only exists when the harpoon window is open

### ISSUE THREAD

**Issue by danielreis1** [ThePrimeagen/harpoon#306]
I would love to start harpoon window with my hotkey, afterwards press 1-9 to pick a choice of what happens next, (having a hotkey that only works while the harpoon window exists (or several in this case the number 1-9 to pick the corresponding option)), but I am unsure of how to do this with this plugin, I managed to have a hotkey that only works when the window is open with a telescope plugin, so I would think it is possible.
Anyone has any guidance on how to accomplish this?
Thank you

**Comment by tg0h** [comment]
open the harpooon menu, then press `:set ft`. you will notice that the harpoon menu has a filetype of harpoon. this means that you can set keymaps specific to the harpoon menu using the file type plugin.

create a ftplugin fille for the harpoon filetype
![Screenshot 2023-08-14 at 14 03 27 - kitty@2x](https://github.com/ThePrimeagen/harpoon/assets/7954426/318d4282-d396-4353-87a1-3b3415b854d7)

create a keymap for the harpoon filetype, eg 2 opens harpoon item 2 
(2G means go to line number 2, <CR> means open ...)
```vim.api.nvim_buf_set_keymap(0, 'n', '2', '2G<CR>', { desc = 'open harpoon item 2' })```

**Comment by danielreis1** [comment]
thanks, that's what I needed to learn more about
