### ISSUE TITLE
This fixed it for me as well. As far as I can  tell there are no problems caused by this workaround.

### ISSUE THREAD

**Issue by GusJelly** [ThePrimeagen/harpoon#324]
Nevermind.
I got it fixed by adding `'` at line 18
in 
`...data\site\pack\packer\start\harpoon/lua/harpoon/init.lua`

from
`'BufLeave, VimLeave'`
to
`'BufLeave', 'VimLeave'`
Now, the harpoon worked again.

_Originally posted by @Yvey in https://github.com/ThePrimeagen/harpoon/issues/323#issuecomment-1754877613_

**Comment by ThePrimeagen** [comment]
yes, i am considering the rewrite of harpoon

harpoon 2 should have a lot of these issues fixed
