### ISSUE TITLE
harpoon error on starting nvim, error invalid event: BufLeave, VimLeave

### ISSUE THREAD

**Issue by AtosPedro** [ThePrimeagen/harpoon#326]
Error detected while processing BufEnter Autocommands for "*":
Failed to run `config` for harpoon

...edro/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:18: Invalid 'event': 'BufLeave, VimLeave'

 stacktrace:
  /harpoon/lua/harpoon/init.lua:18
  /harpoon/lua/harpoon/mark.lua:1
  ~/.config/nvim/lua/custom/plugins/harpoon.lua:4 _in_ **config**
  ~/.config/nvim/init.lua:28
Press ENTER or type command to continue

my harpoon config:
return {
  "theprimeagen/harpoon",
  config = function()
    local mark = require("harpoon.mark")
    local ui = require("harpoon.ui")

    vim.keymap.set("n", "<leader>mh", mark.add_file, { desc = "Harpoon mark" })
    vim.keymap.set("n", "<leader><Tab>", ui.toggle_quick_menu, { desc = "Harpoon Menu" })
    vim.keymap.set("n", "<Tab>1", function() ui.nav_file(1) end, { desc = "Harpoon go to mark 1" })
    vim.keymap.set("n", "<Tab>2", function() ui.nav_file(2) end, { desc = "Harpoon go to mark 2" })
    vim.keymap.set("n", "<Tab>3", function() ui.nav_file(3) end, { desc = "Harpoon go to mark 3" })
    vim.keymap.set("n", "<Tab>4", function() ui.nav_file(4) end, { desc = "Harpoon go to mark 4" })
  end,
}

**Comment by arnevm123** [comment]
This seems to be a duplicate of #323 
If you get the latest version of Harpoon this should be fixed.
This was the fix: #321

**Comment by AtosPedro** [comment]
Ok, thank you for the feedback
