### ISSUE TITLE
[Feature request] multiple harpoons

### ISSUE THREAD

**Issue by mlp1802** [ThePrimeagen/harpoon#327]
Similar to Mylyn for eclipse, having multiple mark lists, depending on the task at hand. Right now you just have one great list of marks, would be nice if you could group them depending on the task at hand, so you can easily switch context.

**Comment by Pranav-Badrinathan** [comment]
I'm curious, what use case would this be for? Currently your marks already depend on what folder you launch nvim from, which already provides a lot of flexibility imo.

By "task at hand" in a projects do you mean, for example, in big projects with dozens of files you want to group files in a mark-lists by tasks, and have multiple lists to quick switch what you are working on?

**Comment by mlp1802** [comment]
Well it's very simple, harpoon gives you a single list. That list will mostly be of files "of interest to a certain task/area". You switch "area of interest" multiple time during a day, rendering the list useless. I couldn't wait for primeagen to implement it so I just made my own. This one also filters the files in nvim-tree.
https://github.com/mlp1802/periscope.nvim

**Comment by mlp1802** [comment]
Got tired of waiting for this, so I just made my own :) 
https://github.com/mlp1802/periscope.nvim
