### ISSUE TITLE
Proposed Logo

### ISSUE THREAD

**Issue by ryanwinchester** [ThePrimeagen/harpoon#329]
I propose a logo/icon:

https://x.com/ryanrwinchester/status/1720459176634118565?s=20

GRAPHIC DESIGN IS MY PASSION

## Logo white bg

![harpoon-logo-wht](https://github.com/ThePrimeagen/harpoon/assets/2897340/119a974f-6d56-412b-8a71-0101905f64b9)

## Logo transparent bg

![harpoon-logo-trns](https://github.com/ThePrimeagen/harpoon/assets/2897340/d0d613a3-a6de-441e-ab74-0d7c4f5c2db6)

## Icon transparent bg

![harpoon-man-icon](https://github.com/ThePrimeagen/harpoon/assets/2897340/1fe58f4e-c8dd-400e-919b-64ce9f6e9e44)

## Icon white bg

![harpoon-icon-wh](https://github.com/ThePrimeagen/harpoon/assets/2897340/d88e7a84-7f8b-4e43-b79c-b302245683c6)

**Comment by Spitfire1900** [comment]
CC-BY-SA?

**Comment by ryanwinchester** [comment]
> CC-BY-SA?

@ThePrimeagen can have it and apply whatever license he wants

**Comment by all123all** [comment]
Wow, this actually looks impressive.

**Comment by ThePrimeagen** [comment]
i will use this @ryanwinchester BUT!!! i need you to make this pr against harpoon2

Let me first get it in.

**Comment by andrecastelo** [comment]
looks awesome @ryanwinchester !

**Comment by ThePrimeagen** [comment]
@ryanwinchester get the PR up for harpoon2
its becoming the main stay shortly

**Comment by ryanwinchester** [comment]
so lighter font for dark mode I guess
![harpoon-logo-trns](https://github.com/ThePrimeagen/harpoon/assets/2897340/a58ab8ee-2c2e-432a-b375-b18328aba555)
![harpoon-logo-trns-drk](https://github.com/ThePrimeagen/harpoon/assets/2897340/80fc3ff3-bcbb-48a0-8fdb-5e30b7890256)
