### ISSUE TITLE
has this been abandoned?

### ISSUE THREAD

**Issue by manugch** [ThePrimeagen/harpoon#336]
Why did the developer stop working on the Harpoon project?
Because every time he tried to "fork" it, he ended up getting caught by deez nuts!

**Comment by pascalisenschmid** [comment]
gotteeeem

**Comment by anott03** [comment]
with all due respect, I am also interested in the answer

**Comment by rockyzhang24** [comment]
As of this moment, ThePrimeagen is live-streaming on twitch the Harpoon v2 development.

**Comment by haloboy777** [comment]
it is

**Comment by daltondiaz** [comment]
Harpoon is active more than EVER!! SO SHUUUUUUUUUUUUUUUUUUUT UP!!

**Comment by WarrenBuffering** [comment]
+1

**Comment by WarrenBuffering** [comment]
bump

**Comment by boozedog** [comment]
With all due respect, +1 / bump (same thing)

**Comment by realzvqle** [comment]
i will rewrite harpoon in rust so it can compile to lua code because we all know rust is rust

**Comment by stordahl** [comment]
![](https://media2.giphy.com/media/4bjJU3luFseGzebz72/giphy.gif?cid=ecf05e471bx9vdu14jfxbz0bbxwxclttvuon0z7wvvek4u02&ep=v1_gifs_search&rid=giphy.gif&ct=g)
