### ISSUE TITLE
is this dead?

### ISSUE THREAD

**Issue by a-rbsn** [ThePrimeagen/harpoon#337]
like no issues from the past year have been answered?

**Comment by rockyzhang24** [comment]
As of this moment, ThePrimeagen is live-streaming on twitch the Harpoon v2 development.

And this https://github.com/ThePrimeagen/harpoon/issues/322 maybe helpful.

**Comment by a-rbsn** [comment]
gotteeeeeeeeem

**Comment by rockyzhang24** [comment]
yaya
