### ISSUE TITLE
Disable insert mode on quick menu

### ISSUE THREAD

**Issue by doganalper** [ThePrimeagen/harpoon#340]
It looks like it is possible to change file names on quick menu by entering insert mode and this results to opening invalid files. Anyway to disable text changes on quick menu maybe make it open as readonly? Would it affect removing buffer marks with `dd` mapping?

**Comment by ThePrimeagen** [comment]
i will be addressing this in harpoon 2,

i'll mark this question as harpoon2 to do :)

**Comment by doganalper** [comment]
@ThePrimeagen Great, thanks!

**Comment by ThePrimeagen** [comment]
@doganalper i could disable writing to quick files, but this would result in not being able to delete lines.

i am unsure if this is really a good idea, so i am going to close this down, you can reopen if you really feel like you would want nomodifiable buffers
