### ISSUE TITLE
Harpoon 2 - Full Path Now Shown In Harpoon Window

### ISSUE THREAD

**Issue by jesses-code-adventures** [ThePrimeagen/harpoon#345]
Giving harpoon 2 a test run this morning and it's been very smooth so far, but aesthetically I liked how harpoon 1 showed truncated filenames in the window rather than the full path.

Please feel free to close the issue if this is intended behaviour !

Harpoon 1 Example
<img width="971" alt="Screen Shot 2023-12-01 at 1 03 20 pm" src="https://github.com/ThePrimeagen/harpoon/assets/113159758/af1542c7-c0e3-4376-bea1-215f496f1e8d">

Harpoon 2 Example
<img width="692" alt="Screen Shot 2023-12-01 at 1 01 14 pm" src="https://github.com/ThePrimeagen/harpoon/assets/113159758/5c3eec28-0488-4705-bf49-c37e390b4106">

**Comment by ThePrimeagen** [comment]
i know what this is, should be an easy fix

**Comment by jesses-code-adventures** [comment]
thank you kindly!
