### ISSUE TITLE
Harpoon 2 - Bring Back Clear List

### ISSUE THREAD

**Issue by jesses-code-adventures** [ThePrimeagen/harpoon#346]
I used to use harpoon.mark.clear_all() very regularly in Harpoon 1, and it would be nice for harpoon/list to have a similar function. Possibly list():remove(items)  is the way to do this, but I haven't been able to work out the right configuration for it.

**Comment by ThePrimeagen** [comment]
oh snap!  yes, that is an easy fix!

**Comment by ThePrimeagen** [comment]
and done
