### ISSUE TITLE
Harpoon 2 list won't stick when deleting or rearrange files

### ISSUE THREAD

**Issue by piraz** [ThePrimeagen/harpoon#348]
When I have some files on my harpoon list like those:

![Screenshot from 2023-12-01 00-17-02](https://github.com/ThePrimeagen/harpoon/assets/715641/47a52b05-6282-4f73-99f3-78339d208d54)

And I delete or rearrange them like:

![Screenshot from 2023-12-01 00-18-06](https://github.com/ThePrimeagen/harpoon/assets/715641/b93af27a-c7bb-4ae4-8d38-46f0a1bb7aa1)
![Screenshot from 2023-12-01 00-18-25](https://github.com/ThePrimeagen/harpoon/assets/715641/508aa6af-9cab-45f9-874b-47b48da562ac)

When I leave the list(`esc` or `q`) and show the list again, the list will be displayed like the first state(first screenshot).

The behavior on Harpoon 1 was to keep the list saved on those cases.

**Comment by ThePrimeagen** [comment]
@piraz Ohh snap!  how did you normally leave your list?  I guess that is the question.  i may have accidentally broke the behavior of this :)

**Comment by fn3x** [comment]
Yep, same here with just the `esc`

**Comment by ThePrimeagen** [comment]
ok, i'll add in this option!  fix incoming

**Comment by ThePrimeagen** [comment]
should be fixed

**Comment by ThePrimeagen** [comment]
assume fixed

you have to enable the option `save_on_toggle`

```lua
harpoon:setup({
  settings = {
    save_on_toggle = true
  }
})
```

`save_on_change` is silly name

**Comment by piraz** [comment]
Nice! Thank you very much.

**Comment by fn3x** [comment]
Thank you <3
