### ISSUE TITLE
Telescope integration

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/harpoon#351]
With the new changes to harpoon2 telescope integration is broken.  anyone that is willing to make the change i'll be glad to accept pr

**Comment by roeeyn** [comment]
@ThePrimeagen I just created the PR #363 

It may not be as cool as htmx, but it's working

**Comment by kiryph** [comment]
How can I map `:Telescope harpoon marks` to a key in lua?

**Comment by roeeyn** [comment]
@kiryph AFAIK, the new version doesn't have the marks attribute anymore. Now, you must use something like this:

```lua
local harpoon = require 'harpoon'
harpoon:setup()

-- Add current buffer to harpoon marks
harpoon:list():append()
```

Here's a [module](https://github.com/roeeyn/dotfiles/blob/070ca74c2d1630dc96f61602d05cddbe49aa2289/dot/.config/nvim/lua/roeeyn/plugins/harpoon.lua) I created for the harpoon config in my dotfiles, and here it is how I [configured](https://github.com/roeeyn/dotfiles/blob/070ca74c2d1630dc96f61602d05cddbe49aa2289/dot/.config/nvim/lua/roeeyn/plugins/which_key.lua#L106-L117) it with the which key plugin.

Basic Example:

```lua
local harpoon = require 'harpoon'
harpoon:setup()

local map = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }

-- Mark the current file with Harpoon
map('n', '<leader>a', ":lua require('harpoon'):list():append()<CR>", opts)
```

**Comment by kiryph** [comment]
@roeeyn Thanks for your comment. I will look into your config. It seems to have what I am looking for:

```
f = { '<cmd>lua require("roeeyn.plugins.harpoon").telescope()<cr>', 'Search in marks' },
```
