### ISSUE TITLE
Automatic movement to harpooned point

### ISSUE THREAD

**Issue by tris203** [ThePrimeagen/harpoon#353]
Getting an issue where in insert mode, you will be randomly moved back to where your harpooned point is.

Deleting the harpoon stops it from jumping

steps to reproduce

1. open nvim
2. set harpoon point
3. exit nvim
4. reload nvim
5. harpoon back to file
6. J down a few lines, enter insert mode
7. type a few characters
8. cursor is pinged back to point
9. delete harpoon point (dd enter)
10. pinging still continues
11. Close and reopen nvim again
12. open file with telescope or similar
13. pinging stops

**Comment by ThePrimeagen** [comment]
Could you include your configuration? The entire harpoon section?

I have yet to experience this, and I've been using it for the last 2 days.

**Comment by hackastak** [comment]
I'm using Lazy as well so I tried to mimic the config here, yet still no luck reproducing the behavior. @ThePrimeagen were you able to replicate yet? 
@tris203 We could move this to the Discord channel to troubleshoot if you're open

**Comment by tris203** [comment]
Further testing, it's not all the time but it seems to be reproducible with this file in particular
and for some reason, it always line 19.

I thought it was the harpooned point, but its not. It jumps me back specifically to line 19

**Comment by ThePrimeagen** [comment]
I have experienced where I was pulled back to a similar point over and over again after playing a game, and that is because I left the game early

**Comment by tris203** [comment]
> Are you playing vim be good?

No @ThePrimeagen 

I haven't even got VimBeGood installed

It only seems to be in this one specific file

**Comment by ThePrimeagen** [comment]
To prove it's from harpoon, you can add a simple print statement in the config.lua file

Lua/harpoon/config.lua

Find the defined select function in the default configuration, I am on phone so I am not going to go grab it

And add at the top of the select function

```lua
print("Hello, Harpoon")
```

**Comment by ThePrimeagen** [comment]
`:messages`

You should see it in the bottom of your screen

**Comment by tris203** [comment]
> Found it, not a harpoon bug Incompatibility with alpha-nvim
> 
> harpooning from the dashboard directly is what causes the wierdness
