### ISSUE TITLE
Allow customizing UI borders 

### ISSUE THREAD

**Issue by trimclain** [ThePrimeagen/harpoon#354]
It would be nice to have the ability to customize borders using one of the options from `:h nvim_open_win()`. I would add the PR myself, I just don't really understand the structure of the config yet and can't see where the `border` option fits the best.

**Comment by ThePrimeagen** [comment]
I can expose this on a per list basis, or globally. Which do you think?

To me, I'm leaning globally

**Comment by trimclain** [comment]
I think globally would be great

**Comment by ThePrimeagen** [comment]
I'll get on this as soon as possible. It might be 48 hours before I get it addressed

**Comment by darianmorat** [comment]
This wasn't merged? It seems that we cannot change it
