### ISSUE TITLE
You gotta decide ;)

### ISSUE THREAD

**Issue by grappas** [ThePrimeagen/harpoon#359]
![obraz](https://github.com/ThePrimeagen/harpoon/assets/1036957/8017d7dd-be29-4663-bef9-bafde4b1b932)

or

![obraz](https://github.com/ThePrimeagen/harpoon/assets/1036957/e8d63160-6505-44d4-9baa-28fa59f52278)

**Comment by ThePrimeagen** [comment]
Very true
