### ISSUE TITLE
Closing quick menu doesn't save unless toggle is called

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/harpoon#36]
Autocmd time!  Lets listen for win close events and ensure that we save upon floating window closed with ZZ/q

**Comment by ThePrimeagen** [comment]
We could also consider using :w as the way you save your changes, that way you can cancel changes made.

thoughts @brandoncc @asbjornhaland ?

**Comment by asbjornCoretrek** [comment]
I agree!

**Comment by asbjornhaland** [comment]
Aah, I see. Yes, I agree. I tried `:w`.

**Comment by brandoncc** [comment]
I should clarify that I'm looking for help getting it to work. It wasn't my intention to be rude :-)

**Comment by brandoncc** [comment]
TJ came to my rescue :-)

I agree that we might want to change to catching buffer saves instead. I'll look into how to do that.

**Comment by brandoncc** [comment]
Here is what I found:

The buffer needs a buffer type to save. I tried `acwrite` and supplying a `BufWriteCmd`:

```lua
vim.cmd(string.format("autocmd BufWriteCmd <buffer=%s> :lua require('harpoon.ui').save_menu_changes()", bufh))
```

This brought a new error saying the buffer doesn't have a file name, so I tried `nofile` -- which makes it fail to save silently.

I tried:

```lua
vim.api.nvim_buf_set_option(bufh, "filename", "harpoon-menu")
```

That brought this:

```
E5108: Error executing lua /Users/brandoncc/dev/harpoon/lua/harpoon/ui.lua:69: Invalid option name 'filename'
```

Any ideas?

**Comment by ThePrimeagen** [comment]
I have never played with this write stuff.  Perhaps this the wrong direct.  

Maybe a local buf keymap?  C-w for writing the file?  We could even put a little message in that window.

**Comment by asbjornhaland** [comment]
Is it possible to make a local cmd `:w` and `:wq` for the buffer?

**Comment by brandoncc** [comment]
@asbjornhaland that's what I was hoping to get from `BufWriteCmd`. I'm not sure if I got close or not.

**Comment by ThePrimeagen** [comment]
I would say this.  

1. Create an api method "save_toggle_menu()" that will save current state.
2. Document it and allow people to call it
3. Allow local remap of ctrl+w to call this method

thoughts?

**Comment by brandoncc** [comment]
What about `save_menu_contents()`? As for the rest, that works for me. I wish I knew how to get the save on write working though, because that is how you want it to work anyway, and the thing that makes the most sense too.

**Comment by asbjornhaland** [comment]
I have a few ideas to try, let me check a little bit.

**Comment by asbjornhaland** [comment]
OK, I think I got it! I'll make an PR you can test if everything works for you as well.
