### ISSUE TITLE
[Feature request] Automatic Mark Population. 

### ISSUE THREAD

**Issue by fullstopslash** [ThePrimeagen/harpoon#361]
First of all this plugin is incredibly useful. I've only just started using it and my mind is spinning with how much faster I'll be able to navigate files in my projects! 

I'm curious if there's currently any capability for automatically populating the project marks list with really common files like todo.md, readme.md and soforth.  What I'm imagining is essentially being able to navigate to a project folder, open nvim, and then map a shortcut to always call up the todo.md for the project I'm in.

**Comment by ThePrimeagen** [comment]
One of the requested features is frecency

I think that could be pretty good along with a common file list. The hard part about a common file list is what files are common?

Definitely do some research on this. It sounds like a pretty fun idea

**Comment by GotaLoveFiraCode** [comment]
This—along with frecency—would be awesome. What I do right now is just to mapping something to `:e todo.md`, but this is sub ideal, and it would be awesome if you could then have the default-files in your harpoon list and edit them accordingly. In other words: +1

**Comment by ThePrimeagen** [comment]
i'll have to think about how this works

**Comment by ThePrimeagen** [comment]
i am going to close this as there is now `harpoon:extend` which allows you to listen to lists being created.  If the default list, `name == require("harpoon.config").DEFAULT_LIST` then you have the default list (or your named list) and you can add files to your hearts content.  

I don't want to build a frecency algorithm into harpoon and this seems like a reasonable extension

:)

**Comment by ThePrimeagen** [comment]
i also have no docs for extensions.  You may have to read the code to accomplish it for now
