### ISSUE TITLE
Harpoon 2 - How Highlight Groups Works? 

### ISSUE THREAD

**Issue by Rafoshi** [ThePrimeagen/harpoon#364]
## Harpoon 2 - How Highlight Groups Works? 

I can't find in the documentation any example of highlight groups being used.

I'm not sure where can I ask this, sorry if the issues is not the right place.

**Comment by patricio-ferraggi-deel** [comment]
you can set any color you want on those groups like this
```lua
        vim.api.nvim_set_hl(0, 'HarpoonBorder', { fg = c.bg_dark, bg = c.bg_dark })
        vim.api.nvim_set_hl(0, 'HarpoonWindow', { fg = c.fg, bg = c.bg_dark })

```

**Comment by Rafoshi** [comment]
Thank you so much
