### ISSUE TITLE
Harpoon stopped working and I haven't changed anything inside my config

### ISSUE THREAD

**Issue by abelkm99** [ThePrimeagen/harpoon#367]
---

**Title:** Harpoon Plugin Not Working in LunarVim

## Description
I've been using the Harpoon plugin with LunarVim, and it recently stopped working. I'm not sure what caused this issue, as it was working fine before.

## LunarVim version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

lvim release-1.3/neovim-0.9

## OS
MAC OS  Sonoma 14.1.1 

## Harpoon and LunarVim Configuration
Here is the relevant part of my `config.lua`:

```lua
lvim.plugins = {
  {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
      require("harpoon").setup()
    end,
  },
}
```
I don't have nothing else inside my config.lua

## Steps to reproduce
1. Open LunarVim with the command `lvim`.

## Expected behavior
Harpoon plugin should load without any errors.

## Screenshots
<img width="859" alt="image" src="https://github.com/ThePrimeagen/harpoon/assets/41730180/41ed933d-614c-4db5-85ad-2f600a48600a">

## Error in Text
Failed to run `config` for harpoon
```
...lunarvim/site/pack/lazy/opt/harpoon/lua/harpoon/init.lua:38: attempt to index local 'self' (a nil value)

# stacktrace:
  - /harpoon/lua/harpoon/init.lua:38 _in_ **setup**
  - ~/.config/lvim/config.lua:7 _in_ **config**
  - ~/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:106
  - ~/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:104 _in_ **load**
  - ~/.local/share/lunarvim/lvim/init.lua:17```
```
---

**Comment by ThePrimeagen** [comment]
please make sure you read the readme

**yours**
```lua
...
harpoon.setup()
...
```

**requirement**
```lua
...
harpoon:setup()
...
```

**Comment by ThePrimeagen** [comment]
i ackshually realize i made the default branch harpoon2 which could of caused this

and if that is the case, i am sorry i broke you (which i now realize its likely my fault)

----

so if you opted into harpoon 2 and then this, make sure you ensure `harpoon:setup()`
if you opened up expecting master, my bad

**Comment by ThePrimeagen** [comment]
i reset the default back to master, this probably was my mistake

**Comment by abelkm99** [comment]
Re-installed Lunarvim, Cleared the cache now everything works as expected.
Thankyou
