### ISSUE TITLE
cannot enter buffer from harpoon popup

### ISSUE THREAD

**Issue by BirdeeHub** [ThePrimeagen/harpoon#369]
The commit hash 80a428855f0852661c55cef7ad53f369d38721f9
is the last working commit for my neovim setup.

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

This first error is fun.

When the logger was first pushed, I got this error.

Commit hash:
6041c605b09dcc31af92524a8f2d4178ec0b8464

```
E5108: Error executing lua ...r/pack/myNeovimPackages/start/harpoon/lua/harpoon/ui.lua:34: attempt to index field 'active_list' (a nil value)
stack traceback:
        ...r/pack/myNeovimPackages/start/harpoon/lua/harpoon/ui.lua:34: in function 'close_menu'
        ...r/pack/myNeovimPackages/start/harpoon/lua/harpoon/ui.lua:131: in function 'select_menu_item'
        [string ":lua"]:1: in main chunk
```

If you hit a key it will still open the file.
HOWEVER, when you go to select it from the menu again, it will open IN THE HARPOON WINDOW
You then cannot close the harpoon window but you can close the buffer within it with :q

Picture attached here:
![lmaoHarpwnd](https://github.com/ThePrimeagen/harpoon/assets/85372418/710a45f6-6657-4063-9174-00f0a9f65448)

on commit hash:
c53305c2d00d0c1dfb5227e8a571cb95b0132fbc

I instead get an error message like this when I hit enter on an item:

E5107: Error loading lua [string ":lua"]:1: ')' expected near '<eof>'

If i press another key, like q which used to close it, 

E5107: Error loading lua [string ":lua"]:1: ')' expected near 'q'

It will not let me close it again except via the harpoon window toggle function
It will not enter the buffer.

It is the same for the most recent commit.

This is my lua config for harpoon

```lua
local harpoon = require("harpoon")

-- REQUIRED
harpoon:setup({})
-- REQUIRED

vim.keymap.set("n", "<leader>ha", function() harpoon:list():append() end, { noremap = true, silent = true, desc = 'append to harpoon' })
vim.keymap.set("n", "<leader>hh", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end, { noremap = true, silent = true, desc = 'open harpoon menu' })

vim.keymap.set("n", "<leader>h1", function() harpoon:list():select(1) end, { noremap = true, silent = true, desc = 'harpoon 1' })
vim.keymap.set("n", "<leader>h2", function() harpoon:list():select(2) end, { noremap = true, silent = true, desc = 'harpoon 2' })
vim.keymap.set("n", "<leader>h3", function() harpoon:list():select(3) end, { noremap = true, silent = true, desc = 'harpoon 3' })
vim.keymap.set("n", "<leader>h4", function() harpoon:list():select(4) end, { noremap = true, silent = true, desc = 'harpoon 4' })
```

I dont know if my loading would be the cause or if its an issue with the logger.

or both. I am using nix to load my config.

My config file is based on this nix neovim config template that I made

It allows people to get the benefits of nix while still using lua for configuration.

[nixCats-nvim](https://github.com/BirdeeHub/nixCats-nvim)

my one is this

[my personal config with the issue](https://github.com/BirdeeHub/birdeevim)

You can download them via nix and they will run. clone it or not, then nix build if you cloned it, or with nix build github:BirdeeHub/birdeevim or nix build github:BirdeeHub/nixCats-nvim

It would build to a folder symlinked to a file named result in the current directory when using the nix build option

birdeevim is the one with the issue. I currently have it locked in the flake input to the commit hash that was working last. 

You could clone it, go to flake.nix, and up near the top replace the hash in your url with harpoon2 and then run nix build, and run it at ./result/bin/nvim to reproduce the issue.

birdeevim will ask you to log into bitwarden for some ai logins, just hit enter a couple times and let it throw an error. Thats fine. That happens in the plugin folder so that the error doesnt break the lua config.

Its not a distribution its my personal config and it says so right on the readme XD

nixCats is the one that is the framework for others.

it loads in the lua config via using the following, which it runs as an init.vim using the -u command line option
```nix
    configDir = if settings.configDirName != null && settings.configDirName != ""
      then settings.configDirName else "nvim";
    customRC = ''
        let configdir = expand('~') . "/.config/${configDir}"
        execute "set runtimepath-=" . configdir
        execute "set runtimepath-=" . configdir . "/after"
      '' + (if settings.wrapRc then ''
        let runtimepath_list = split(&runtimepath, ',')
        call insert(runtimepath_list, "${LuaConfig}", 0)
        let &runtimepath = join(runtimepath_list, ',')

        set runtimepath+=${LuaConfig}/after

        lua package.path = package.path .. ';${LuaConfig}/init.lua'
        lua require('${builtins.baseNameOf LuaConfig}')
      '' else ''
        let runtimepath_list = split(&runtimepath, ',')
        call insert(runtimepath_list, configdir, 0)
        let &runtimepath = join(runtimepath_list, ',')

        execute "set runtimepath+=" . configdir . "/after"

        lua package.path = package.path .. ';' .. vim.api.nvim_get_var('configdir') .. '/init.lua'
        lua require('${configDir}')
      '') + ''
        lua << EOF
        ${optionalLuaAdditions}
        EOF
      '';
```

my stdpath('data') is normal, either $NVIM_APPNAME or nvim, (in which case the variable is not set)
even stdpath('config') would point to the normal directory

but my config is in the nix store like so
```nix
    LuaConfig = pkgs.stdenv.mkDerivation {
      name = builtins.baseNameOf path;
      builder = builtins.toFile "builder.sh" ''
        source $stdenv/setup
        mkdir -p $out
        cp -r ${path}/* $out/
      '';
    };
```
Its been working great for everything else, its pretty cool. Although mason doesnt work on nixOS, which has a couple more debuggers than nix. And lazy doesnt work well because it says you cant re-source your config, but it is rendered completely unnecessary by nix anyway

also, I trolled you a while ago about resolve being res and now I don't even agree with my own point anymore XD But you were a good sport about it thank you id been having a terrible few days and it made my morning.

**Comment by tris203** [comment]
i am having a similar issue right now.
This error if i try to nav from the popup
```
E5107: Error loading lua [string ":lua"]:1: ')' expected near ''
```

Shortcuts work fine for me.
Logger shows a single line
```
"ui#toggle_quick_menu" "__harpoon_files"
```

**Comment by BirdeeHub** [comment]
ok cool so its nothing to do with my flake this is great news

**Comment by BirdeeHub** [comment]
well, at the very least, he can pull my flake to reproduce it if it doesnt reproduce on his machine XD

Oh, im using alacrity. It happens regardless of shell though. havent tested other emulators yet

**Comment by spirodonfl** [comment]
I'm getting a similar (or same) issue:

Details about my setup

* Running WSL2 (on Windows 11) - Ubuntu distro
* NVIM 0.9.4
* Using kickstart.nvim
* Above denotes using lazy plugin manager

Steps to reproduce:

* Running my project
* loading two files into buffer
* appending both files into the harpoon list
* opening menu
* hitting 'enter' key on one item in menu
* getting error - `E5107: Error loading lua [string ":lua"]:1: ')' expected near '<eof>'
* subsequent usage
* - sometimes not able to get back into menu
* - sometimes getting more serious error (below)

```
E5108: Error executing lua: ...ro/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:109: BufLeave Autocommands for "__harpoon*": Vim(append):Error executing lua callback: .../spiro/.local/share/nvim/lazy/harpoon/lua/harpoon/ui.lua:34: attempt to index field 'activ
e_list' (a nil value)
stack traceback:
        .../spiro/.local/share/nvim/lazy/harpoon/lua/harpoon/ui.lua:34: in function 'close_menu'
        .../spiro/.local/share/nvim/lazy/harpoon/lua/harpoon/ui.lua:107: in function 'toggle_quick_menu'
        ...ro/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:102: in function <...ro/.local/share/nvim/lazy/harpoon/lua/harpoon
/buffer.lua:100>
        [C]: in function 'nvim_set_current_buf'
        ...ro/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:109: in function 'select'
        ...piro/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:164: in function 'select'
        /home/spiro/.config/nvim/init.lua:629: in function </home/spiro/.config/nvim/init.lua:629>
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...ro/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:109: in function 'select'
        ...piro/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:164: in function 'select'
        /home/spiro/.config/nvim/init.lua:629: in function </home/spiro/.config/nvim/init.lua:629>
```

Notes:
* Can often exit project and return with a maintained harpoon list
* Sometimes can still use shortcut keys to switch between entries in list

**Comment by ThePrimeagen** [comment]
my fault on this, let me double check it tonight!   i am sorry if i caused any issues to anyone.  feels bad :(

trying to add in observability and i think i goofed

**Comment by ThePrimeagen** [comment]
Hard time with kids, couldn't work on it

**Comment by spirodonfl** [comment]
> Hard time with kids, couldn't work on it

Kids first @ThePrimeagen

**Comment by BirdeeHub** [comment]
All good i have it pinned until you close the issue. It works fine on the old commit. Get when it to you can but don't hurt yourself over it :)

**Comment by ThePrimeagen** [comment]
fixed in latest as well

**Comment by BirdeeHub** [comment]
Can confirm. It is indeed fixed.
