### ISSUE TITLE
Harpoon 2 - q and esc no longer work as escape keys

### ISSUE THREAD

**Issue by jesses-code-adventures** [ThePrimeagen/harpoon#370]
After upgrading to Harpoon 2, attempting to escape the harpoon window returns these lua errors:

q - E5107: Error loading lua [string ":lua"]:1: ')' expected near 'q'
esc - E20: Mark not set

**Comment by ThePrimeagen** [comment]
I have done something, but my kids did some real acting up tonight, so I was unable to fix it, likely in the am for me

**Comment by ThePrimeagen** [comment]
fixed!

**Comment by jesses-code-adventures** [comment]
thank you sir!
