### ISSUE TITLE
How Can I change the width?

### ISSUE THREAD

**Issue by patricio-ferraggi-deel** [ThePrimeagen/harpoon#372]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------

I would like to change the width of the popup menu in harpoon 2, is there a way to do that?
The way for harpoon 1 doesnt seem to work on 2

![image](https://github.com/ThePrimeagen/harpoon/assets/129756134/1ca81a2a-18eb-474f-a24c-b24f986b3927)

**Comment by ThePrimeagen** [comment]
yes, i can allow default width change
