### ISSUE TITLE
Harpoon2 errors out when harpoon.json is empty

### ISSUE THREAD

**Issue by mwishoff** [ThePrimeagen/harpoon#376]
I upgraded from Harpoon to Harpoon2, and somewhere along the line harpoon.json file existed but was empty. I don't know how it got this way, but it did. When the harpoon.json exists and is empty Harpoon errors out due to invalid json in the vim.fn.decode function.

OS: Windows 11
NeoVim: v0.9.4

This can be replicated by doing the following:
1.) Open harpoon.json, delete it's contents, and save the file.
2.) Open Neovim
3.) Attempt to Add a file to the harpoon list or attempt to open the Harpoon telescope window.

The user experience could be better if in the case harpoon.json is an empty file, to reinitialize it with empty json and continue as usual.

**Comment by ThePrimeagen** [comment]
i can special case this one, but i am little worried about just erasing data if json parse error happens here.
