### ISSUE TITLE
Provide feature to change default location of harpoon.json file

### ISSUE THREAD

**Issue by m-deg** [ThePrimeagen/harpoon#380]
I would like to change harpoon.json file location. I have a custom git setup that autocommits and pushes certain files.

I would like my harpoon marks to persist across multiple computers I am using. I was able to hack together something to get this work, but its really ugly. It would be awesome if this was supported out of the box.

**Comment by ThePrimeagen** [comment]
its already there

```lua
require("harpoon.data").set_data_path(full_path)
```

**Comment by ThePrimeagen** [comment]
but this is subject to change in the future with me potentially making every key generated its own file in a harpoon directory.  this would allow me to write to file on every single change instead of waiting for vim to close (anything goes wrong / terminal is closed we may not save)
