### ISSUE TITLE
harpoon2 open in split/tab mappings

### ISSUE THREAD

**Issue by name-snrl** [ThePrimeagen/harpoon#381]
Hello, are there any plans to add these mappings to harpoon 2? Or now I will have to setup it myself through autocmds or any other way?

https://github.com/ThePrimeagen/harpoon/blob/867e212ac153e793f95b316d1731f3ca1894625e/lua/harpoon/init.lua#L32-L54

**Comment by name-snrl** [comment]
I tried adding mapping to `buffer.lua`, like:

```lua
    vim.api.nvim_buf_set_keymap(
        bufnr,
        "n",
        "<C-V>",
        "<Cmd>lua require('harpoon').ui:select_menu_item({ vsplit = true })<CR>",
        {}
    )
```

but it doesn't work properly, #382 fixes that

**Comment by ThePrimeagen** [comment]
so opening in split / tab totally works!  but not from auto-commands.  this is an interesting issue

so #382 is not the way i wish to go about it, but we should be able to extend the config in such a way that when selecting there is a "default" option OR when opening a toggle menu we can pass an `option` for the config select action to be used.

if you have any ideas, glad to see a PR, else i'll try to get to this as one of the many tasks of getting harpoon 2 off the ground

**Comment by ThePrimeagen** [comment]
If this is fixed could you close this down?

**Comment by ThePrimeagen** [comment]
it is fixed based on the PR i just closed

**Comment by name-snrl** [comment]
> it is fixed based on the PR i just closed

This issue requested for a mapping to open files from harpoon UI to (v)split/tab, why are you closing it? There is still no mapping to open files in split or even the ability to add them to harpoon, I don't understand why you think the problem is solved.

**Comment by psaikido** [comment]
This doesn't look like it has been fixed to me. I put the fix in for original harpoon with this commit (https://github.com/ThePrimeagen/harpoon/commit/edf29292da0481ed434a104262592e891c4c028f). I see no way to open a file in a split or tab from harpoon2.
