### ISSUE TITLE
NvimTree broken after harpoon:setup()

### ISSUE THREAD

**Issue by thmshmm** [ThePrimeagen/harpoon#390]
I use NvimTree and wanted to try harpoon2. Just installed the plugin and added `harpoon:setup()`. If I now try to open a file via NvimTree, instead of opening the file it opens the tree again.

Any idea how to fix that?

**Comment by tris203** [comment]
Can you include your config for both harpoon and nvim-tree and the output of

```
:lua require("harpoon").logger:show()
```

After recreating the bug in a fresh nvim instance

**Comment by InfiniteRain** [comment]
I'm also experiencing the same bug, but as per comment in another issue, this is the error I'm getting:

I use neotree instead of nvimtree, but the behaviour is exactly as described in OP, but it also shows me this error.

```
[Neo-tree ERROR] debounce  filesystem_navigate  error:  ...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:180: BufLeave Autocommands for "*": Vim(append):Error executing lu
a callback: Vim:E474: Error while dumping encode_tv2json() argument, key 'refresh_projects_b4update': attempt to dump function reference
stack traceback:
^I[C]: in function 'json_encode'
^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:174: in function 'save'
^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/mark.lua:18: in function 'emit_changed'
^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/mark.lua:281: in function 'store_offset'
^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:20: in function <...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:19>
^I[C]: in function 'nvim_win_set_buf'
^I...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:180: in function '_open_window'
^I...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:249: in function 'mount'
^I.../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1010: in function 'acquire_window'
^I...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:508: in function 'get_items'
^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:89: in function 'follow_internal'
^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:146: in function '_navigate_internal'
^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:176: in function <...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:175>
^I[C]: in function 'pcall'
^I...k/packer/start/neo-tree.nvim/lua/neo-tree/utils/init.lua:126: in function 'debounce'
^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:175: in function 'navigate'
^I...ker/start/neo-tree.nvim/lua/neo-tree/sources/manager.lua:488: in function 'navigate'
^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:203: in function 'do_show_or_focus'
^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:161: in function 'execute'
^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:169: in function '_command'
^I[string ":lua"]:1: in main chunk
```

**Comment by thmshmm** [comment]
> :lua require("harpoon").logger:show()

I enabled only NvimTree and harpoon, and run setup. Trying to enable the logger shows:

`E5108: Error executing lua [string ":lua"]:1: attempt to index field 'logger' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk`

**Comment by InfiniteRain** [comment]
> I'm also experiencing the same bug, but as per comment in another issue, this is the error I'm getting:
> 
> I use neotree instead of nvimtree, but the behaviour is exactly as described in OP, but it also shows me this error.
> 
> ```
> [Neo-tree ERROR] debounce  filesystem_navigate  error:  ...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:180: BufLeave Autocommands for "*": Vim(append):Error executing lu
> a callback: Vim:E474: Error while dumping encode_tv2json() argument, key 'refresh_projects_b4update': attempt to dump function reference
> stack traceback:
> ^I[C]: in function 'json_encode'
> ^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:174: in function 'save'
> ^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/mark.lua:18: in function 'emit_changed'
> ^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/mark.lua:281: in function 'store_offset'
> ^I...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:20: in function <...nvim/site/pack/packer/start/harpoon/lua/harpoon/init.lua:19>
> ^I[C]: in function 'nvim_win_set_buf'
> ^I...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:180: in function '_open_window'
> ^I...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:249: in function 'mount'
> ^I.../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1010: in function 'acquire_window'
> ^I...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:508: in function 'get_items'
> ^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:89: in function 'follow_internal'
> ^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:146: in function '_navigate_internal'
> ^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:176: in function <...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:175>
> ^I[C]: in function 'pcall'
> ^I...k/packer/start/neo-tree.nvim/lua/neo-tree/utils/init.lua:126: in function 'debounce'
> ^I...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:175: in function 'navigate'
> ^I...ker/start/neo-tree.nvim/lua/neo-tree/sources/manager.lua:488: in function 'navigate'
> ^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:203: in function 'do_show_or_focus'
> ^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:161: in function 'execute'
> ^I...packer/start/neo-tree.nvim/lua/neo-tree/command/init.lua:169: in function '_command'
> ^I[string ":lua"]:1: in main chunk
> ```
> 
> This error also appears when I try to access Telescope.

To anyone reading this in the future: I fixed this by upgrading to harpoon 2, the error is now gone and I can use it properly: https://github.com/InfiniteRain/nvim/commit/4aed935cc0c740da99f230bc6d3ea12bd4465ede

**Comment by ThePrimeagen** [comment]
This is definitely a very weird one. Sorry that it happened, and I have no idea how these two things are related. But if anyone is reading it, attempt the advice above

**Comment by haydenrou** [comment]
Just noting for anyone else that sees this... I had a similar error too, using lazy.nvim .

When executing `harpoon:setup()` I got the following error in the logs: `Error executing lua [string ":lua"]:1: attempt to index field 'logger' (a nil value)` - it also broke telescope:

```
E5108: Error executing lua: .../share/nvim/lazy/plenary.nvim/lua/plenary/popup/init.lua:408: BufLeave Autocommands for "*": Vim(append):Error executing lua callback: Vim:E474:
Error while dumping encode_tv2json() argument, key 'refresh_projects_b4update': attempt to dump function reference
stack traceback:
        [C]: in function 'json_encode'
        ...ille/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:174: in function 'save'
        ...ille/.local/share/nvim/lazy/harpoon/lua/harpoon/mark.lua:18: in function 'emit_changed'
        ...ille/.local/share/nvim/lazy/harpoon/lua/harpoon/mark.lua:281: in function 'store_offset'
        ...ille/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:20: in function <...ille/.local/share/nvim/lazy/harpoon/lua/harpoon/init.lua:19>
        [C]: in function 'nvim_set_current_win'
        .../share/nvim/lazy/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:331: in function '_create_window'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:401: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:541: in function <.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:500>
stack traceback:
        [C]: in function 'nvim_set_current_win'
        .../share/nvim/lazy/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:331: in function '_create_window'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:401: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:541: in function <.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:500>
```

Reinstalling and changing the target branch to `harpoon2` fixed this issue for me too.

```
{'ThePrimeagen/harpoon', branch = 'harpoon2'}
```

**Comment by ctfrancia** [comment]
I followed @thmshmm advice of removing the harpoon plugin and then adding it again and it all worked fine for me

**Comment by ghost** [comment]
Alright, I encountered the same issue, and I resolved it by switching to the harpoon2 branch using `git switch harpoon2` from @brentmitchell25 . Everything seems to be working fine now. Thank you so much!
