### ISSUE TITLE
Nothing is listed in ui but it is listed in telescope.

### ISSUE THREAD

**Issue by niksingh710** [ThePrimeagen/harpoon#393]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------
![image](https://github.com/ThePrimeagen/harpoon/assets/60490474/5c065f52-2218-4d6e-b3aa-8e6fd2866a67)
![image](https://github.com/ThePrimeagen/harpoon/assets/60490474/8421ac72-e3f2-4382-8078-c4a89ddb5e56)

**Comment by willothy** [comment]
Can you try the `fix-ui` branch of my fork (from #392) and see if this is still happening?

**Comment by niksingh710** [comment]
> Can you try the `fix-ui` branch of my fork (from #392) and see if this is still happening?

on ur branch i am getting error while creating a mark
![image](https://github.com/ThePrimeagen/harpoon/assets/60490474/4e773f5f-a3c1-4727-b5b4-f24bcb38af7d)

![image](https://github.com/ThePrimeagen/harpoon/assets/60490474/497a415f-5d66-45dc-8f92-673aaa475131)

opening ui gives this error (there isn't any mark because of first error but without marks blank ui should open)

**Comment by willothy** [comment]
That's probably in your config, `harpoon.marks` is no longer a function. My bad, was this issue related to harpoon v1?

**Comment by niksingh710** [comment]
> harpoon:list():append()

this is teh mapping set i am using 
```lua
{
		["<leader>fm"] = { ":lua require('harpoon.mark').add_file()<cr>", "Mark file to harpoon" },
		["<leader>fu"] = { ":lua require('harpoon.ui').toggle_quick_menu()<cr>", "Harpoon Ui" },
		["<leader>ff"] = { ":Telescope harpoon marks<cr>", "Harpoon Telescope" },
	},
```

able to mark by using `harpoon:list():append()`
but unabel to toggle quick menu

**Comment by willothy** [comment]
Note the semicolon in my prior response. Here's what you can use:

```lua
{
  ["<leader>fm"] = { ":lua require('harpoon'):list():append()<cr>", "Mark file to harpoon" },
  ["<leader>fu"] = { ":lua require('harpoon').ui:toggle_quick_menu()<cr>", "Harpoon Ui" },
  ["<leader>ff"] = { ":Telescope harpoon marks<cr>", "Harpoon Telescope" },
},
```

You need to access the configured harpoon UI through the root module with `require("harpoon").ui`.

**Comment by niksingh710** [comment]
> Note the colon in my prior response. Here's what you can use:
> 
> ```lua
> {
>   ["<leader>fm"] = { ":lua require('harpoon'):list():append()<cr>", "Mark file to harpoon" },
>   ["<leader>fu"] = { ":lua require('harpoon').ui:toggle_quick_menu(require('harpoon'):list())<cr>", "Harpoon Ui" },
>   ["<leader>ff"] = { ":Telescope harpoon marks<cr>", "Harpoon Telescope" },
> },
> ```
> 
> You need to access the configured harpoon UI through the root module with `require("harpoon").ui`.

yeah can tell now it is working.
![image](https://github.com/ThePrimeagen/harpoon/assets/60490474/104aa5e0-3461-49f0-9b9b-aa98f3a36ce3)
but now in telescope it is now showing numbers

**Comment by willothy** [comment]
Telescope shows line numbers for me as well, likely a new change in v2. Nothing to do with my fork. Glad it's working!

**Comment by niksingh710** [comment]
> Telescope shows line numbers for me as well, likely a new change in v2. Nothing to do with my fork. Glad it's working!
> 
> The line numbers are the saved cursor positions in each file.

Aah, then fine should be closing this issue as soon as the pr is merged then.

**Comment by niksingh710** [comment]
on merging of #392 this is resolved.
