### ISSUE TITLE
Relative/line numbers disappears in branch2

### ISSUE THREAD

**Issue by desdic** [ThePrimeagen/harpoon#409]
so I just did a very default installation of harpoon branch harpoon2 and if I open vim, press ctrl+e to toggle_quick_menu and open the 2 files I have, the first one gets line numbers but the second does not get numbers.

If both files are open already then no issue both have line numbers .. so its only when it has to open the second buffer I get this issue

**Comment by theKnightsOfRohan** [comment]
I'm not able to replicate this with either relative or normal line numbers. Can you try updating harpoon2, and seeing if it persists? If so, it might be a plugin conflict.

**Comment by desdic** [comment]
you are right, I'm sorry .. its nvimdev/dashboard-nvim that conflicts
