### ISSUE TITLE
[QUESTION] Not syncing list moving out of the popup, is that expected?

### ISSUE THREAD

**Issue by patricio-ferraggi-deel** [ThePrimeagen/harpoon#415]
I am having an issue where if I delete an item in the list while in the popup menu, and then move out of the toggle menu to an open buffer the item in the list is not deleted, when I open the list again it shows up again. If on the other hand I delete the item the list and then select one of the remaining items then the item is correctly deleted, is this expected? I would like to sync the list when I move out of it.

![ezgif com-video-to-gif-converted](https://github.com/ThePrimeagen/harpoon/assets/129756134/f2ba133d-5153-402a-bc2a-7524c0f83827)

**Comment by tris203** [comment]
Existing the list doesn't sync it.

You can either select an item to cnnfirm or :w to save the list

**Comment by patricio-ferraggi-deel** [comment]
it would nice to have a config to enable this to be honest, I would love to sync on exit

**Comment by daltondiaz** [comment]
@patricio-ferraggi-deel  try to add the following configuration:

```lua
harpoon:setup({
    settings = {
        save_on_toggle = true
    }
})
```
So you don't need to use :w
