### ISSUE TITLE
Switch over master to harpoon2

### ISSUE THREAD

**Issue by theKnightsOfRohan** [ThePrimeagen/harpoon#418]
**What issue are you having that you need harpoon to solve?**
Cloning and forking and stuff to fiddle with harpoon can get really annoying when harpoon2 is basically a feature branch, and thus is not the default.

**Why doesn't the current config help?**
Because harpoon2 is not the default branch.

**What proposed api changes are you suggesting?**
Move harpoon to a separate branch, maybe called legacy, and make harpoon2 master.

**Comment by willothy** [comment]
I think this is the plan once harpoon2 is more stable - it shouldn't be difficult though, you can just tag the `harpoon2` branch with your package manager...

**Comment by ThePrimeagen** [comment]
I've been unable to address any harpoon PRs or issues in the last few days.

We can get through the majority of issues then I will make the upgrade. I also need to address the terminal launching, boo
