### ISSUE TITLE
shutdown -r now 

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/harpoon#43]
I have had the file saving process not work 2x `shutdown -r now`.  Perhaps we should consider on every update to the harpoon mark config.  We could use Path's async save

Thoughts @asbjornhaland @brandoncc

**Comment by asbjornhaland** [comment]
Wow. That's not good. I did not experience any of that throughout my workday today. Does it hang? What did you do when it broke?

**Comment by ThePrimeagen** [comment]
Effectively the previous state the config file was in remains.  The updating doesn't seem to happen, no hanging.

**Comment by asbjornhaland** [comment]
How do you close the window - toggle, `:wq`?

**Comment by ThePrimeagen** [comment]
Ahh!  I see the confusion.

No.  So I have vim running in some terminal.  I have made several changes to the marks.  I then go to another terminal and type `shutdown -r now`.  This will erase any progress made on marks since the vimleave didn't get the time it needed to write a file.

**Comment by asbjornhaland** [comment]
Sounds about right. The object is updated all the time, but is only written to disk on `VimLeavePre`.

**Comment by asbjornhaland** [comment]
What do we think about this now? Should we save to disk more often, or?
