### ISSUE TITLE
Harpoon2: Unset a keymap for ui harpoon window

### ISSUE THREAD

**Issue by arnevm123** [ThePrimeagen/harpoon#431]
Hi,

I don't think there's currently a native way to unset the escape key from closing the UI. I spam my escape sometimes, which can cause some accidental closes.
My current workaround is this (did not work without defer_fn):
```
vim.api.nvim_create_autocmd("FileType", {
	desc = "Don't close harpoon menu with 'esc'",
	pattern = { "harpoon" },
	callback = function()
		vim.defer_fn(function()
			vim.keymap.set("n", "<esc>", "", { silent = true, buffer = true })
		end, 100)
	end,
})
```
I think these could be made optional or even configurable if you'd want to support this:
https://github.com/ThePrimeagen/harpoon/blob/9031087ff1b18d0a34bd664719ec66cc8be1efd8/lua/harpoon/buffer.lua#L52-L62

I can look into implementing this if this is something you'd like.
If not, you can close the issue, as I have a workaround for myself.

**Comment by ThePrimeagen** [comment]
I'm thinking about pulling out this code anyways and creating an extension for people to use.

That way this isn't the default behavior.

**Comment by ThePrimeagen** [comment]
I should have a night in the next 10 days to work on this.

**Comment by ianebeckett** [comment]
I came here to report a symptom of the same(?) issue: I accidentally opened netrw in the harpoon UI.

**Comment by arnevm123** [comment]
This is a cleaner solution for this issue (so the opposite of what you'll actually configure in the end I guess) :smile: :
```
harpoon:extend({
	UI_CREATE = function(cx)
		vim.keymap.set("n", "<esc>", "", { buffer = cx.bufnr })
	end,
})
```

**Comment by ThePrimeagen** [comment]
That's the goal, I'm going to create an extensions part of harpoon for the commonly used ones

This seems like a good place.
