### ISSUE TITLE
[Harpoon 2] Quick menu automatically closing on open

### ISSUE THREAD

**Issue by tjbarber** [ThePrimeagen/harpoon#434]
Config is the same as the one in the `README`, and the only other plugin I have installed at the moment is [auto-save.nvim](https://github.com/Pocco81/auto-save.nvim). Here is what the logger is outputting:

```
ui#toggle_quick_menu#opening __harpoon_files
ui#save { "nvim/after/plugin/harpoon.lua", "nvim/after/plugin/lsp-zero.lua", "kitty/current-theme.conf", "kitty/kitty.conf", ".git-blame-ignore-revs", ".alacritty.linux.yml", ".alacritty.darwin.yml" }
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 4, win = 1002 }
toggle by BufLeave
ui#toggle_quick_menu#closing
```

`auto-save.nvim` automatically saves the current open buffer when the mode changes, so what I'm gathering is that harpoon somehow triggers the auto save but closes when the file is saved. Is there a way to disable that or not listen for file writes to determine if the quick menu should be closed?

**Comment by theKnightsOfRohan** [comment]
This should be caused by this block in `lua/harpoon/buffer.lua`, line 64. I guess you could disable autosave triggering when entering a harpoon buffer, or only triggering when leaving the buffer, not opening it. Would you be able to share your autosave config? 

```lua
vim.api.nvim_create_autocmd({ "BufWriteCmd" }, {
    group = HarpoonGroup,
    buffer = bufnr,
    callback = function()
        require("harpoon").ui:save()
        vim.schedule(function()
            require("harpoon").logger:log("toggle by BufWriteCmd")
            require("harpoon").ui:toggle_quick_menu()
        end)
    end,
})
```

**Comment by willothy** [comment]
> `auto-save.nvim` automatically saves the current open buffer when the mode changes, so what I'm gathering is that harpoon somehow triggers the auto save but closes when the file is saved. Is there a way to disable that or not listen for file writes to determine if the quick menu should be closed?

`auto-save.nvim` probably shouldn't be auto-saving non-normal buffers in the first place... imo this is something that should be addressed in that plugin. I check buftype and use `noautocmd write` in my autosave plugin to avoid this.

You should be able to prevent this behavior in your config by adding those checks to the `condition` function in your `auto-save.nvim` config. Something like this:

```lua
condition = function(buf)
  if vim.bo[buf].filetype == "harpoon" then
    return false
  end
  -- ... the rest of your condition code
end
```

You could also disable auto-save for all non-normal buffers by returning false if `buftype ~= ""` instead.

**Comment by tjbarber** [comment]
Thank both of you for your help, @theKnightsOfRohan @willothy!

Adding a condition that check for the "harpoon" filetype does fix this.

**Comment by cvonsteg** [comment]
Was having a similar issue.  When I used the above solutions it fixed my harpoon issues but then auto-save started throwing invalid buffer exceptions when a floating window was opened.  To address both I eventually just left the default auto-save condition block with 1 minor change:

```lua

condition = function(buf)
    local fn = vim.fn
    local utils = require("auto-save.utils.data")

    if
        fn.getbufvar(buf, "&modifiable") == 1 and 
         -- change here is adding harpoon file type to exclusion list 
        utils.not_in(fn.getbufvar(buf, "&filetype"), {"harpoon"}) then
        return true
    end
    return false
end
```

(pls excuse formatting, having to send from phone)

**Comment by flowfelis** [comment]
> > `auto-save.nvim` automatically saves the current open buffer when the mode changes, so what I'm gathering is that harpoon somehow triggers the auto save but closes when the file is saved. Is there a way to disable that or not listen for file writes to determine if the quick menu should be closed?
> 
> `auto-save.nvim` probably shouldn't be auto-saving non-normal buffers in the first place... imo this is something that should be addressed in that plugin. I check buftype and use `noautocmd write` in my autosave plugin to avoid this.
> 
> You should be able to prevent this behavior in your config by adding those checks to the `condition` function in your `auto-save.nvim` config. Something like this:
> 
> condition = function(buf)
>   if vim.bo[buf].filetype == "harpoon" then
>     return false
>   end
>   -- ... the rest of your condition code
> end
> You could also disable auto-save for all non-normal buffers by returning false if `buftype ~= ""` instead.

Thank you for this. 

To resolve this issue I implemented opening harpoon again in snacks picker. Pasting here in case someone needs:
```
return {
  "ThePrimeagen/harpoon",
  branch = "harpoon2",
  dependencies = { "nvim-lua/plenary.nvim" },
  keys = function()
    local status_ok, harpoon = pcall(require, "harpoon")
    if not status_ok then
      return
    end
    -- picker
    local function generate_harpoon_picker()
      local file_paths = {}
      for _, item in ipairs(harpoon:list().items) do
        table.insert(file_paths, {
          text = item.value,
          file = item.value,
        })
      end
      return file_paths
    end
    local keys = {
      {
        "<leader>H",
        function()
          require("harpoon"):list():add()
          local filename = vim.fn.expand("%:t")
          vim.api.nvim_echo({
            { "Harpooned the shit out of ", "None" },
            { filename, "Title" }, -- Title is often bold in most color schemes
          }, false, {})
        end,
        desc = "Harpoon File",
      },
      {
        "<leader>fh",
        function()
          Snacks.picker({
            finder = generate_harpoon_picker,
            win = {
              input = {
                keys = {
                  ["dd"] = { "harpoon_delete", mode = { "n", "x" } },
                },
              },
              list = {
                keys = {
                  ["dd"] = { "harpoon_delete", mode = { "n", "x" } },
                },
              },
            },
            actions = {
              harpoon_delete = function(picker, item)
                local to_remove = item or picker:selected()
                table.remove(harpoon:list().items, to_remove.idx)
                picker:find({
                  refresh = true, -- refresh picker after removing values
                })
              end,
            },
          })
        end,
      },
    }
    for i = 1, 5 do
      table.insert(keys, {
        "<leader>" .. i,
        function()
          require("harpoon"):list():select(i)
        end,
        desc = "Harpoon to File " .. i,
      })
    end
    return keys
  end,
}

```
