### ISSUE TITLE
File opened with Harpoon can't be folded (E490: No fold found)

### ISSUE THREAD

**Issue by gonstoll** [ThePrimeagen/harpoon#443]
I reallyyyyyy want to use `harpoon` (or harpoon2 if you will 😅) as I love it so much, but I can't get around this issue. 

I use [oil.nvim](https://github.com/stevearc/oil.nvim) as my file explorer (my config [here](https://github.com/gonstoll/dotfiles/blob/harpoon-test/nvim/lua/plugins/oil.lua)) overriding `netrw`.

When I enter Neovim and are presented with oil's file explorer, I fire `harpoon` to take me to x file. When doing so, folds don't seem to appear. As soon as I go into insert mode, the folds appear out of nowhere and I'm off to the races. But I gotta do this on a per-file basis and it get's quite overwhelming.

You can find my entire config [here](https://github.com/gonstoll/dotfiles/tree/harpoon-test/nvim). Could I be missing something that's not harpoon related maybe?

**Comment by gonstoll** [comment]
Here's a recording of what I mean

https://github.com/ThePrimeagen/harpoon/assets/25900010/88c8e371-91e8-458f-8b7d-55473a4b2e31

**Comment by ThePrimeagen** [comment]
Harpoon simply opens a buffer. It doesn't do anything special. If there's something special you wish to have happened upon opening a file, you need to override the configuration, check out the select command on the default list config

**Comment by gonstoll** [comment]
@ThePrimeagen thanks for the reply! I solved it by doing this:

```lua
harpoon:setup({
  ufo = {
    select = function(list_item, list, option)
      local bufnr = vim.fn.bufnr(list_item.value)
      local set_position = false

      if bufnr == -1 then
        set_position = true
        bufnr = vim.fn.bufnr(list_item.value, true)
      end
      if not vim.api.nvim_buf_is_loaded(bufnr) then
        vim.fn.bufload(bufnr)
        vim.api.nvim_set_option_value('buflisted', true, {
          buf = bufnr,
        })
      end

      vim.api.nvim_set_current_buf(bufnr)

      if set_position then
        vim.api.nvim_win_set_cursor(0, {
          list_item.context.row or 1,
          list_item.context.col or 0,
        })
      end

      vim.cmd('UfoEnableFold') -- Custom behavior
    end
  }
})
```

Basically I head to the default config, copy/pasta it, and added the `vim.cmd('UfoEnableFold')` at the end. Would that be a correct approach? What I don't like about this is that if the default config changes I won't get any of that :/

Also, I don't see a way to leverage items from this list on the `:extend()` method:

```lua
harpoon:extend({
  UI_CREATE = function(cx)
    km(
      '<C-v>',
      function() harpoon.ui:select_menu_item({vsplit = true}) end, -- How can I select items from the 'ufo' list here?
      {desc = 'Open as vertical split', buffer = cx.bufnr}
    )
    km(
      '<C-x>',
      function() harpoon.ui:select_menu_item({split = true}) end,
      {desc = 'Open as split', buffer = cx.bufnr}
    )
    km(
      '<C-t>',
      function() harpoon.ui:select_menu_item({tabedit = true}) end,
      {desc = 'Open in new tab', buffer = cx.bufnr}
    )
  end,
})
```

**Comment by ThePrimeagen** [comment]
What do you need for me to extend harpoon for you? I could add a new method

**Comment by ThePrimeagen** [comment]
https://github.com/ThePrimeagen/harpoon/blob/31701337377991c66eebb57ebd23ef01eb587352/lua/harpoon/config.lua#L92

I just have to add a new event in this function that emits out the buffer, I believe

**Comment by gonstoll** [comment]
I'm not really sure what'd be the right approach, not that experienced on vim plugin development 😅 I think I'm ok with how it got solved, but in essence all I need is for [ufo](https://github.com/kevinhwang91/nvim-ufo) to be enabled every time I enter a buffer with harpoon. I figured this can also be done with an autocommand, but (to the best of my knowledge) that'd be triggered on **every** `BufEnter`, not just harpooned files.

Maybe a `BufEnter` method on the list config is an valid option?

**Comment by gonstoll** [comment]
@ThePrimeagen awesome, works like a charm ✨ thanks a lot for adding this!

Could it maybe have broken the other events being emitted with `:extend`? For example, opening files with `vsplit` ain't working anymore.

How my config looks:
```lua
harpoon:extend(extensions.builtins.command_on_nav('UfoEnableFold'))
harpoon:extend({
  UI_CREATE = function(cx)
    vim.keymap.set(
      'n',
      '<C-v>',
      function()
        harpoon.ui:select_menu_item({vsplit = true})
      end,
      {desc = 'Open as vertical split', buffer = cx.bufnr}
    )
    vim.keymap.set(
      'n',
      '<C-x>',
      function() harpoon.ui:select_menu_item({split = true}) end,
      {desc = 'Open as split', buffer = cx.bufnr}
    )
    vim.keymap.set(
      'n',
      '<C-t>',
      function() harpoon.ui:select_menu_item({tabedit = true}) end,
      {desc = 'Open in new tab', buffer = cx.bufnr}
    )
  end,
  -- Also tried using NAVIGATE event here instead of extensions.builtins, same luck
})
```

Logger shows this:
```
config_default#select { context = { col = 0, row = 1 }, value = "nvim/lua/plugins/harpoon.lua" } __harpoon_files
ui#toggle_quick_menu#opening __harpoon_files
ui#select_menu_item selecting item 2 from { "nvim/lua/plugins/harpoon.lua", "nvim/lua/plugins/oil.lua" } options { vsplit = true }
config_default#select { context = { col = 0, row = 1 }, value = "nvim/lua/plugins/oil.lua" } __harpoon_files { vsplit = true }
toggle by BufLeave
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 5, win = 1002 }
ui#close_menu name: nil win and bufnr {}
```

**Comment by gonstoll** [comment]
Never mind, nuked harpoon and restarted everything and now it works. @ThePrimeagen thanks a lot again! By the way I love your stuff man, you are the reason I started learning vim this year so I have a lot to be thankful from you 🙏

**Comment by moeezali2375** [comment]
@gonstoll, what's the fix for code folding? I'm using UFO for code folding in Neovim, but when I open a buffer with Harpoon, code folding doesn't work. I have a keymap set to <z><a> to toggle folds, but it doesn't function. I'm noob to Neovim, so could you please help me resolve this issue?
