### ISSUE TITLE
VsCode

### ISSUE THREAD

**Issue by Nightshadedude** [ThePrimeagen/harpoon#445]
**What issue are you having that you need harpoon to solve?**
This doesn't work with VSCode

**Why doesn't the current config help?**
This doesn't work with VSCode

**What proposed api changes are you suggesting?**
Make it work with VSCode

**Comment by ThePrimeagen** [comment]
i'll have to quit my job, learn months of windows development, make love to Microsoft, and use a plebs editor to understand what this even means

I am sick of these entitled roblox kids
