### ISSUE TITLE
Can't set position after relaunch.

### ISSUE THREAD

**Issue by Nybkox** [ThePrimeagen/harpoon#459]
When I start Neovim with no open buffers and use harpoon2 to select an item, two buffers open: one is empty and the other shows the selected file. I also get an error during this. Selecting other items afterward works without any issues.

If open any other buffer before harpooning it also works fine.

This occurs in a fresh LazyVim install with the latest harpoon2 commit. Have anyone encountered that using LazyVim?

```
E5108: Error executing lua: ...local/share/nvimlazy/lazy/harpoon/lua/harpoon/config.lua:128: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...local/share/nvimlazy/lazy/harpoon/lua/harpoon/config.lua:128: in function 'select'
        .../.local/share/nvimlazy/lazy/harpoon/lua/harpoon/list.lua:182: in function 'select'
        .../nybkox/.config/nvimlazy/lua/plugins/editor/harpoon2.lua:42: in function <.../nybkox/.config/nvimlazy/lua/plugins/editor/harpoon2.lua:41>
```

Logger:
`config_default#select { context = { col = 0, row = 322 }, value = "frontend/src/common/survey/surveyValidator/nfieldSurveyValidator.js" } __harpoon_files`

**Comment by ThePrimeagen** [comment]
I wanted to program tonight, but it may have to be tomorrow

**Comment by lpanebr** [comment]
perhaps related to #441 ? 
If so, fixing will give Prime a close bonus! 😉

**Comment by Nybkox** [comment]
Seems to be broken by a new empty buffer opened by neotree, setting hijack_netrw_behavior to open_curent in the neotree config fixes that.
```
filesystem = {
              hijack_netrw_behavior = "open_current",
 },
```

**Comment by amesaine** [comment]
Had a similar problem but with a different error.

```
E5108: Error executing lua: ...um/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:145: attempt to get length of a nil value
stack traceback:
  ...um/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:145: in function 'select'
  ...raum/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:295: in function 'select'
  .../braum/.local/share/nvim/lazy/harpoon/lua/harpoon/ui.lua:189: in function 'select_menu_item'
  ...um/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:21: in function 'run_select_command'
  ...um/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:61: in function <...um/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:60>
```

Same error message as https://github.com/ThePrimeagen/harpoon/issues/534#issuecomment-2094840234

Reinstalling both neotree and harpoon at the same time fixes the problem. The default setting `open_default` works properly now.
