### ISSUE TITLE
Harpoon 2: Harpoon 2 creates multiple instance on every new directory.

### ISSUE THREAD

**Issue by roshanlimbu** [ThePrimeagen/harpoon#465]
when i  harpoon files in a directory and move to next directory the harpoon initiates a new instance and i can't toggle to the previous harpooned files. I need to go the the previous directory again and only can i  again toggle between harpooned files.

**Comment by ThePrimeagen** [comment]
This sounds like you should have the exact same problem in your previous version.

You must have whatever the vim command to update your current directory to your current file.

autocwd? 

You could override the settings key.  I'm on mobile right now but I can help provide an example in a bit

**Comment by maxrzaw** [comment]
If you are using neotree and you don't want to change your harpoon key, you need to change `bind_to_cwd` to be false in the setup method because it will change your cwd. `{ filesystem = { bind_to_cwd = false } }`

**Comment by roshanlimbu** [comment]
Thanks its solved
