### ISSUE TITLE
[Harpoon.nvim]: Issue with files in the git folder

### ISSUE THREAD

**Issue by nrupatunga** [ThePrimeagen/harpoon#473]
Im using Harpoon2 in Neovim. Im facing an issue.

To share an example, the files are in two different folders. Both are under the same git repository.

`root/folder1/ex1.lua` and `root/folder2/ex2.lua`

when I open the harpoon list I do not see two files `ex1.lua, ex2.lua` as I expect. But I only see one depending on which folder my vim is in currently.

Does anyone know what could be the issue,? or if my understanding is wrong?

**Comment by arnevm123** [comment]
Harpoon2 gets it root directory from get get_root_dir function.
The default function just takes your vim.loop.cwd().
You have to change your get_root_dir to something like this if you want it to use your git root:
```
harpoon:setup({
	default = {
		get_root_dir = function ()
			local cwd = vim.loop.cwd()
			local root = vim.fn.system("git rev-parse --show-toplevel")
			if vim.v.shell_error == 0 and root ~= nil then
				return string.gsub(root, "\n", "")
			end
			return cwd
    		end
    	}
})
```

**Comment by nrupatunga** [comment]
I tried the above solution, but still doesn't seem to work yet.

**Comment by arnevm123** [comment]
Hmmm, what is your output for `:pwd`?
Are you navigating to root/folder1 in nvim and then adding them?
and is your root folder a git folder?

It could also help to remove the harpoon.json ( should be in this folder: `lua print(vim.fn.stdpath("data"))`)

**Comment by nrupatunga** [comment]
yes, I deleted and tried it. they are in git folder

here is my dot files: https://github.com/nrupatunga/nvim

**Comment by arnevm123** [comment]
Hmmm, I had a look, but everything looks okay. Not sure what's wrong :/

**Comment by nrupatunga** [comment]
The bug is in my config. setting the `autochdir=false` fixed it.
