### ISSUE TITLE
New issue templates aren't showing up

### ISSUE THREAD

**Issue by theKnightsOfRohan** [ThePrimeagen/harpoon#479]
We moved #456 from master to harpoon2, but the new issue templates aren't showing up when an issue is created. I did some digging, and as I stated in #456 when I reopened it, issue templates [must be placed in the master branch](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). So, #456 should also be merged in, or the swap should occur soon.

**Comment by ThePrimeagen** [comment]
yes, they will not be until i make harpoon2 the default branch, which i will shortly.  I am just not interested in that quite yet.  As of now, i have let harpoon2 simmer for some without any errors on my usage

i will probably make the merge to master sooner than later
