### ISSUE TITLE
add mouse support

### ISSUE THREAD

**Issue by ghost** [ThePrimeagen/harpoon#482]
There are several reasons why using a mouse instead of a keyboard can be a good idea:

    Enhanced precision: A mouse allows for precise pointing and clicking, which can be beneficial in tasks that require accuracy, such as graphic design or photo editing. It offers fine-grained control for selecting small areas or objects on the screen.

    Improved navigation: Navigating through complex interfaces or websites is generally easier with a mouse. It allows for smooth scrolling, quick access to hyperlinks, and intuitive exploration of menus and options.

    Versatility: Mice often come with multiple buttons or customizable features, enabling users to perform various actions with a single click. This versatility makes it easier to execute shortcuts, control multimedia playback, or switch between applications effortlessly.

    Ergonomics: Mice are designed to fit naturally under the user's hand, providing comfort during prolonged use. This ergonomic design helps prevent repetitive strain injuries and reduces the risk of discomfort or fatigue compared to typing extensively on a keyboard.

    Graphic and design work: For tasks involving graphical elements, such as drawing, 3D modeling, or CAD applications, a mouse provides better control and precision over the cursor's movement, allowing for more detailed and accurate creations.

    Gaming: Many games are optimized for mouse input, providing intuitive controls for aiming, selecting objects, or moving characters. The mouse's sensitivity and fluid movement make it a preferred choice for gamers, providing a more immersive and responsive experience.

    Accessibility: Using a mouse can be particularly advantageous for individuals with certain physical disabilities or limitations, such as limited mobility or dexterity. A mouse can offer an alternative input method, making it easier for these users to interact with computers and software.

While keyboards also have their own advantages, such as text input and quick access to shortcuts, the mouse excels in tasks requiring precision, navigation, and graphical manipulation. Therefore, combining the use of a mouse and a keyboard provides a balanced and efficient approach to interacting with computers and software.

**Comment by Nybkox** [comment]
small d energy
