### ISSUE TITLE
Can I get a way to rename harpoons list items so that it is easy for me fuzzy find the list?

### ISSUE THREAD

**Issue by shibisuriya** [ThePrimeagen/harpoon#488]
**What issue are you having that you need harpoon to solve?**
Sometimes I have a long list of harpoon items, I use telescope to fuzzy find items from this list, but this gets overwhelming since I have to remember the file names, what if we were able to rename the items so that it is easy for me to search through the list... 

**Why doesn't the current config help?**

**What proposed api changes are you suggesting?**

**Comment by ThePrimeagen** [comment]
sorry, not interested in this change.

you need to prune your list from time to time, or else its just another file system (and we don't need that)
