### ISSUE TITLE
Deleted files from list remain on list when pressing q to exit Harpoon

### ISSUE THREAD

**Issue by funnie-monkey** [ThePrimeagen/harpoon#492]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------
![GIF Maker from Imgflip](https://github.com/ThePrimeagen/harpoon/assets/41880357/79115771-7b00-4ad9-b1a3-5bf93d076a3e)

As shown in the gif. First time deleting the files, I exit using q but I can still jump to the files. The second time, I delete the files and press enter. That's when the deleted files don't appear anymore. 

If that's the intended behavior then that's ok, I just wanted to make sure that if it was, then it can possibly be fixed.

**Comment by funnie-monkey** [comment]
Gif looks really small so here's the actual video
https://github.com/ThePrimeagen/harpoon/assets/41880357/a555aa4a-a97b-4941-81be-81c7622aa8fe

**Comment by rnwtn** [comment]
I noticed this too, and am wondering if it's intentional. Like, 'q' is to close and discard changes. Writing to the harpoon buffer saves your changes though.

**Comment by rnwtn** [comment]
> I noticed this too, and am wondering if it's intentional. Like, 'q' is to close and discard changes. Writing to the harpoon buffer saves your changes though.

There's a similar issue open here https://github.com/ThePrimeagen/harpoon/issues/433

Looks like there's a couple settings you can use to get the functionality you want. `save_on_toggle` and `sync_on_ui_close`. I haven't tried it though. https://github.com/ThePrimeagen/harpoon/issues/433#issuecomment-1861759784

**Comment by funnie-monkey** [comment]
> > I noticed this too, and am wondering if it's intentional. Like, 'q' is to close and discard changes. Writing to the harpoon buffer saves your changes though.
> 
> There's a similar issue open here #433
> 
> Looks like there's a couple settings you can use to get the functionality you want. `save_on_toggle` and `sync_on_ui_close`. I haven't tried it though. [#433 (comment)](https://github.com/ThePrimeagen/harpoon/issues/433#issuecomment-1861759784)

Ok, then yea, seems like the behavior is on purpose and save_on_toggle is what I'll need to use. Thanks for letting me know @rnwtn !!!
