### ISSUE TITLE
[Harpoon 2] There is any way to do the same thing as mark_branch from Harpoon?

### ISSUE THREAD

**Issue by marcioflaviof** [ThePrimeagen/harpoon#502]
Hello guys, thanks for this awesome plugin, one feature that I used a lot from the original Harpoon was `mark_branch` but I didn't see anything like that on Harpoon2, there is any way in Harpoon2 to get this feature?

**Comment by erik-ahlburg-schmidt** [comment]
Hi @marcioflaviof,

i was also missing this feature, but eventually found a quick way to add the functionality to harpoon2! I have looked into the main branch how the `mark_branch` feature actually works. In Harpoon2 you can specify HarpoonSettings key to tell harpoon how the out list key is looked up.

Here is my config (note that I am using lazy.nvim as my package manager):
```lua
local Job = require "plenary.job"

local function get_os_command_output(cmd, cwd)
  if type(cmd) ~= "table" then return {} end
  local command = table.remove(cmd, 1)
  local stderr = {}
  local stdout, ret = Job:new({
    command = command,
    args = cmd,
    cwd = cwd,
    on_stderr = function(_, data) table.insert(stderr, data) end,
  }):sync()
  return stdout, ret, stderr
end

return {
  {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    opts = {
      settings = {
        save_on_toggle = true,
        sync_on_ui_close = true,
        key = function()
          local branch = get_os_command_output({
            "git",
            "rev-parse",
            "--abbrev-ref",
            "HEAD",
          })[1]

          if branch then
            return vim.loop.cwd() .. "-" .. branch
          else
            return vim.loop.cwd()
          end
        end,
      },
    },
  }
```

Hope this helps!

**Comment by marcioflaviof** [comment]
It worked here, thanks @erik-schmidt

**Comment by D0T7** [comment]
@erik-schmidt 
 `return vim.loop.cwd()` doesn't work on neovim `v0.10.0`, instead I'm using `return vim.fn.getcwd()` 
Also using this function leads to the loss of the marked files after rebooting nvim, any ideas on why that might be?

**Comment by marcioflaviof** [comment]
> @erik-schmidt `return vim.loop.cwd()` doesn't work on neovim `v0.10.0`, instead I'm using `return vim.fn.getcwd()` Also using this function leads to the loss of the marked files after rebooting nvim, any ideas on why that might be?

Maybe it can be something related to this
- https://github.com/ThePrimeagen/harpoon/issues/577
