### ISSUE TITLE
Truncate long path names

### ISSUE THREAD

**Issue by idelice** [ThePrimeagen/harpoon#520]
I would love to truncate long path names as they can be _very_ long in some cases and makes it impossible to see the actual file name that I harpoon'ed.

**Comment by YasarKantarcilar** [comment]
got same problem cuz my laptops with is not big enough to fit all the path and it overflows. so fixed the problem with -- init.lua

-- ... (other configurations)

require("harpoon").setup({
    menu = {
        width = 40,  -- Adjust this value based on your preferences
    }
})

-- ... (other configurations)

**Comment by jcdampil23** [comment]
https://github.com/ThePrimeagen/harpoon/issues/523#issuecomment-1984926994

Here is a way to truncate the directory path
