### ISSUE TITLE
BufWinEnter error when using select(1) followed by select(3)

### ISSUE THREAD

**Issue by parkerbedlan** [ThePrimeagen/harpoon#521]
Right after opening nvim, when I use the keymap for `select(1)` followed by the keymap for `select(3)`, or `select(3)` followed by `select(1)`, I get this error:

```
E5108: Error executing lua: BufWinEnter Autocommands for "*"..function <SNR>18_Highlight_Matching_Pair, line 149: Vim(call):E801: ID already taken: 3
stack traceback:
        [C]: in function 'bufload'
        ...im/site/pack/packer/start/harpoon/lua/harpoon/config.lua:111: in function 'select'
        ...nvim/site/pack/packer/start/harpoon/lua/harpoon/list.lua:182: in function 'select'
        /home/pk/.config/nvim/after/plugin/harpoon.lua:13: in function </home/pk/.config/nvim/after/plugin/har
poon.lua:13>
```

I can hit Enter and go on with my life, and the error doesn't pop up again until I close and reopen nvim again. Keep in mind it's only an issue for `select(1)` and `select(3)` when paired together. Here are my configurations:
```
-- .config/nvim/lua/pk/packer.lua
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function(use)
    -- ...
    use {
        "ThePrimeagen/harpoon",
        branch = "harpoon2",
        requires = { { "nvim-lua/plenary.nvim" } }
    }
    -- ...
end)

-- .config/nvim/after/plugin/harpoon.lua
local harpoon = require("harpoon")
harpoon:setup()

vim.keymap.set("n", "<leader>a", function() harpoon:list():append() end)
vim.keymap.set("n", "<C-\\>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)

vim.keymap.set("n", "<C-h>", function() harpoon:list():select(1) end)
vim.keymap.set("n", "<C-j>", function() harpoon:list():select(2) end)
vim.keymap.set("n", "<C-k>", function() harpoon:list():select(3) end)
vim.keymap.set("n", "<C-l>", function() harpoon:list():select(4) end)

vim.keymap.set("n", "<C-S-P>", function() harpoon:list():prev() end)
vim.keymap.set("n", "<C-S-N>", function() harpoon:list():next() end)
```

**Comment by ktzee** [comment]
I have a similar issue, but I managed to narrow it down. I wonder if it's the same for you.  
I noticed that the error is about: 18_Highlight_Matching_Pair  
I then noticed that the files I was using started with pairs of brackets.  
So I tried:

harpoon 3 files with content that starts with matching pairs: I get the error when first opening nvim and harpooning back and forth. As you said, I can press enter and keep going, it works fine.  
harpoon 3 files with content that does NOT start with matching pairs: I don't get any error.  

I don't know how to fix this yet, but at this point I'm not even completely sure this is a harpoon problem.  

Edit: however, switching between these files *without* using harpoon, doesn't reproduce the issue. So there probably is something in the select() function that causes this?

**Comment by ktzee** [comment]
Small update: I ran :NoMatchParen before trying to reproduce the issue and it indeed does not reproduce.

**Comment by ktzee** [comment]
Last update: I worked it around for now by:
Disabling the built-in matchparen plugin: vim.g.loaded_matchparen = 1
Installing this matchparen plugin: https://github.com/monkoose/matchparen.nvim

**Comment by Amleto** [comment]
I wonder if this is somehow related

https://github.com/vim/vim/issues/5335

Edit: I retract that 😅

**Comment by ktzee** [comment]
It's clearly not harpoon at this point. I unfortunately don't feel like I understand where the bug might be to file an issue in the right place. I guess maybe the built in matching parens plugin?

**Comment by parkerbedlan** [comment]
> Last update: I worked it around for now by: Disabling the built-in matchparen plugin: vim.g.loaded_matchparen = 1 Installing this matchparen plugin: https://github.com/monkoose/matchparen.nvim

This worked for me, thanks! It's odd that nvim's built-in parentheses matching plugin doesn't play well with Harpoon.
