### ISSUE TITLE
Error on `harpoon.ui:toggle_quick_menu(harpoon:list())`

### ISSUE THREAD

**Issue by chris-dem** [ThePrimeagen/harpoon#526]
I am using Windows nvim and I followed the default configurations. Every time I try to open the Harpoon menu, I get this error
```
E5108: Error executing lua: ...m-data\site\pack\packer\start\harpoon/lua/harpoon/ui.lua:99: invalid key: title
stack traceback:
        [C]: in function 'nvim_open_win'
        ...m-data\site\pack\packer\start\harpoon/lua/harpoon/ui.lua:99: in function '_create_window'
        ...m-data\site\pack\packer\start\harpoon/lua/harpoon/ui.lua:147: in function 'toggle_quick_menu'
        ~\AppData\Local\nvim\after\plugin\harpoon.lua:8: in function <~\AppData\Local\nvim\after\plugin\harpoon.lua:8>         
```

**Comment by efenny** [comment]
I encountered this error as well and was able to resolve it by updating NVIM to v0.9.5

**Comment by chris-dem** [comment]
Winget says that I am using neovim v0.9.5 but I am still getting that error. I am using PowerShell 7 if that helps

**Comment by chris-dem** [comment]
Ok turns out I had multiple versions and I was using the wrong one. Thank you!

**Comment by hristod** [comment]
I have the same issue on Mac, with nvim v0.10.0 and everything updated. Any ideas how to fix it?

**Comment by thekbbohara** [comment]
same error. have latest version of nvim-> ❯ nvim -v
NVIM v0.10.3
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Run "nvim -V1 -v" for more info
