### ISSUE TITLE
remove all files with harpoon2?

### ISSUE THREAD

**Issue by TomSchimana** [ThePrimeagen/harpoon#527]
`harpoon:list():remove()` removes the file of the current buffer from Harpoon. How can I remove all files in Harpoon2?

**Comment by Roconx** [comment]
harpoon:list():clear() is probably what you are looking for

**Comment by TomSchimana** [comment]
Thanks. Is there a list of the calls? Especially since I want to integrate Harpoon2 into Lualine and the ones from version 1 don't work anymore. Unfortunately, I haven't found anything.

**Comment by Roconx** [comment]
Not that I know of. You should look at the source code, especially [lua/harpoon/list.lua](https://github.com/ThePrimeagen/harpoon/blob/harpoon2/lua/harpoon/list.lua). 
If you are unable to make it work, let me know what you want to do, as I might be able to help.

**Comment by TomSchimana** [comment]
Thanks. Everything works now.
