### ISSUE TITLE
gr (go to references) vim builtin shortcut broken by harpoon2

### ISSUE THREAD

**Issue by barnii77** [ThePrimeagen/harpoon#529]
# Description
When I use harpoon, my `gr` shortcut breaks.

# Lunarvim
I use [Lunarvim](https://github.com/LunarVim/LunarVim), a Neovim distro (I think it's pretty cool)

# Videos
I have appended a video of what my editor looks like with and without harpoon enabled.

## With harpoon enabled
https://github.com/ThePrimeagen/harpoon/assets/96374414/0f5e81d0-1ded-4904-ae6b-6951dcd3ef80

## Without harpoon
https://github.com/ThePrimeagen/harpoon/assets/96374414/bec9b49a-f82c-4cc3-8036-110334ccae8d

# My Config
If the rest of my config is relevant, it can be found [here](https://github.com/barnii77/config.lvim)

**Comment by ThePrimeagen** [comment]
harpoon does not override any keys other than within the harpoon window itself.  whatever you have done is the issue.  i don't have time to go through your config and debug why you are not having your `gr` working.  i suggest `rg`ing for `gr` to see if you have other shortcuts setup for this

**Comment by barnii77** [comment]
Alright, thank you. The problem is that with Lunarvim, most of my keyboard shortcuts are preconfigured, so I don't really know what it does under the hood. I'll probably try updating to the newest lunarvim version and see if that helps... thanks for the support :)
