### ISSUE TITLE
Normalizing of paths not done in Bufleave

### ISSUE THREAD

**Issue by lars-vc** [ThePrimeagen/harpoon#530]
In the creation of a list item, the path gets normalized, at least on the first creation of an item.
![image](https://github.com/ThePrimeagen/harpoon/assets/57136208/1077d94c-4d39-4ed2-8303-e39c62ba8091)
But later when bufleave is called this is not normalized again. This causes the get_by_display function to return nil.
![image](https://github.com/ThePrimeagen/harpoon/assets/57136208/bf56fa23-5116-4e25-bf08-7fc9252fd002)
I propose adding a line like this:
`bufname = normalize_path(bufname, list.config.get_root_dir())`
Once this is resolved, I will also create a pullrequest for #417

**Comment by ThePrimeagen** [comment]
feel free to pr this and i'll merge this change.  i _think_ that makes sense (i hope).  file names are _really_ hard

sometimes vim is like "here is a relative" and then others its "absolute time!"

**Comment by lars-vc** [comment]
I have done some more manual testing, and it should indeed be normalized. The reason harpoon still works is because nvim automatically puts your cursor at the last position of that buffer and not because of this code
![image](https://github.com/ThePrimeagen/harpoon/assets/57136208/fc7df55d-c532-4ca8-84c7-39ad63637947)

**Comment by lars-vc** [comment]
Ah it seems you have already added this change last week :+1:

**Comment by kimabrandt-flx** [comment]
I experience a noticeable lag - when switching buffers - after the change from `nvim_buf_get_name` to `normalize_path`!
Is anyone else unhappy with this change?
<strike>Could, using the `bufnr` of opened buffers for switching, be worth looking into?! Or is it too much or unwanted complexity?</strike>

**Comment by lars-vc** [comment]
mmmh, I would assume this is more due to the fact that the code to store the position actual runs now. As the normalize_path function is just this:
```lua
local function normalize_path(buf_name, root)
    return Path:new(buf_name):make_relative(root)
end
```
How noticeable is your lag? Personally, I do not notice it.

**Comment by kimabrandt-flx** [comment]
@lars-vc You're right! The lag is not caused by `normalize_path()`, but rather the call to `Extensions.extensions:emit()` -> `Data:sync()`.
