### ISSUE TITLE
How to only save the harpoon file in disk, when it is changed

### ISSUE THREAD

**Issue by leosmaia21** [ThePrimeagen/harpoon#531]
Hello,
At my work the disk where is have my config(neovim, plugins,etc) is quite too slow, so i was wondering if there was some way, of only rewrite the json file when the harpoon list is changed, also i would like to disable the cursor save position, it is another thing that make the experience not so good because of the disk speed.
Resuming i would like to harpoon to save the files i add, when the list is changed and nothing more.

Thank you

**Comment by ThePrimeagen** [comment]
I'm going to be changing how harpoon is stored. Stay tuned, hopefully I can get this out in a couple weeks

**Comment by ThePrimeagen** [comment]
this is now the default behavior of harpoon. 

we sha256 all `config.settings.key()` as a file allowing for per project files and allowing for saving upon every change

**Comment by leosmaia21** [comment]
Hello, but is it possible to not save upon every change? i would like only to save the harpoon files and nothing more, and save on fs only when the list is changed, i dont want it to save the cursor position, my disk access is quite slow at work (it is nfs ...).

Thank you for responding.
