### ISSUE TITLE
Just updated harpoon and KABOOM!

### ISSUE THREAD

**Issue by wildfunctions** [ThePrimeagen/harpoon#546]
Lazy just now pulled a harpoon update, and when I tried to poon a file from my menu, got this explosion:

```
E5108: Error executing lua: ...bkim/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:242: 'for' limit must be a number
stack traceback:
        ...bkim/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:242: in function 'resolve_displayed'
        ...e/bkim/.local/share/nvim/lazy/harpoon/lua/harpoon/ui.lua:170: in function 'select_menu_item'
        ...im/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:21: in function 'run_select_command'
        ...im/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:61: in function <...im/.local/share/nvim/lazy/harpoon/lua/harpoon/buffer.lua:60>
```

**Comment by tommitah-heeros** [comment]
Looks like `HarpoonUI:select_menu_item()`'s usage of `HarpoonList:resolve_displayed()` is missing the second argument, which would be the length of the table. You can just add `#list` as a second argument to it and you'll be good to go. Could make a pr for this.

Blazing fast edit: looks like there already is a PR for this.

**Comment by Spacejet13** [comment]
I spent far too long looking for breaking changes that I had not adapted to in my config that was causing this error. Glad to see there is a PR already.

**Comment by ThePrimeagen** [comment]
dude... i goofed.  is this still an issue.  i have updated harpoon and have several tests but i don't see this error at all
