### ISSUE TITLE
File with extra file extension is routed to the file without the extra file extension on reload

### ISSUE THREAD

**Issue by daveHylde** [ThePrimeagen/harpoon#548]
Setup: I'm on Harpoon2 using LazyVim's config.

Reproduce:
1) Harpoon two files where one has an extra file-extension (in this case '.cs') like this: 
![image](https://github.com/ThePrimeagen/harpoon/assets/95252506/66cf1dd3-ec2d-4ce6-bf9c-b5791b39d494)

2) quit and reopen Neovim

3) When harpooning to either file you will get routed to the file without the extra file extension.

Final note: I know this example is using razor and C#. I'm so sorry.

**Comment by ThePrimeagen** [comment]
i'll take a look at this.  i am trying to round the bases for harpoon2

**Comment by daveHylde** [comment]
It looks like it was fixed overnight, can see that lazy had a bunch of updates for me this morning - one was for harpoon:
![image](https://github.com/ThePrimeagen/harpoon/assets/95252506/8a2df35e-3b9f-47b2-8d07-3bb9b9a34261)

It works fine now - thanks for writing a great plugin! 

And thanks for being awesome! I'm a fan and follower. (I wanted to add an emoji here, but then remembered that we're all grown men here)

> note: I can see that I wrote it wrong - the routing was always to the file WITH the extra ext

**Comment by ThePrimeagen** [comment]
Thank you.

Not only that, harpoon should always be saving per navigation

**Comment by daveHylde** [comment]
Yeah, I have noticed it not doing that a few times where the cursor is reset to 1:1. 
Not sure if it's related but I've run into this a few times after the updates: 
```
E5108: Error executing lua: ...id/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:133: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...id/.local/share/nvim/lazy/harpoon/lua/harpoon/config.lua:133: in function 'select'
	...avid/.local/share/nvim/lazy/harpoon/lua/harpoon/list.lua:277: in function 'select'
	/home/david/.config/nvim/lua/plugins/harpoon.lua:42: in function </home/david/.config/nvim/lua/plugins/harpoon.lua:41>
```
But this is happening randomly without any clear pattern to reproduce it.

When this error occurs in a harpooned file, and you navigate to that same currently active file, then the cursor is moved to 1:1.
