### ISSUE TITLE
[harpoon2] Request: Option to hide the 'saving { "example.txt" }' text being printed upon closing quick menu

### ISSUE THREAD

**Issue by ptdewey** [ThePrimeagen/harpoon#549]
Setup: 
- Harpoon2 on commit: [4ad05be](https://github.com/ThePrimeagen/harpoon/commit/4ad05be8fe98092f0dec3bc3b47abebb59c3814a)

Issue:
- After updating to the most recent version of harpoon 2, every time the quick menu is closed a message is printed to the command line saying 'saved { "example.txt" }'. It appears to print out the current contents of the harpoon table.

Cause:
- Opening the harpoon quick menu - `harpoon.ui:toggle_quick_menu(harpoon:list())`

It appears to be coming from this newly added line in lua/harpoon/ui.lua, at line 196
```lua
print("saving", vim.inspect(list))
```

I like the idea of being able to enable this as an option (probably for debugging), but I don't think it should be the default behavior.

**Comment by ThePrimeagen** [comment]
changed and accidentally let that in :)
