### ISSUE TITLE
The harpoon list can have the wrong length

### ISSUE THREAD

**Issue by abeldekat** [ThePrimeagen/harpoon#555]
https://github.com/ThePrimeagen/harpoon/assets/58370433/60aa60e3-21e1-4595-9bf2-08b52b1b09cc

Hello @ThePrimeagen,

First off, thanks for merging this [PR](https://github.com/ThePrimeagen/harpoon/pull/541)

Using my plugin [harpoonline](https://github.com/abeldekat/harpoonline), I discovered that the length of the list can be wrong. I [use](https://github.com/abeldekat/harpoonline/blob/a92580198152c56717772e64c90a01efe23656b4/lua/harpoonline/init.lua#L203):

```lua
require("harpoon"):list():length()
```

Up until recently this was working just fine.

See the video.

Reproduce:

1. Start from scratch
2. Harpoon 2 files
3. Open the UI
4. Delete both files
5. Reopen the UI: No items
6. Notice that `harpoonline` still shows `1`: -> The latest call to `length` returned 1. See this [code fragment](https://github.com/abeldekat/harpoonline/blob/a92580198152c56717772e64c90a01efe23656b4/lua/harpoonline/init.lua#L262)
7. Use vim.print and notice that the length of the list is indeed 1 instead of 0

**Comment by ThePrimeagen** [comment]
Should be easy fix

**Comment by abeldekat** [comment]
I included a [test](https://github.com/abeldekat/harpoonline/blob/f7615e6e323d67c5b2873826564e7bf3299ea1db/tests/test_harpoonline.lua#L140) for this scenario in the [Harpoonline](https://github.com/abeldekat/harpoonline) plugin.

**Comment by abeldekat** [comment]
When implementing [toggle](https://github.com/abeldekat/nvim_pde/blob/13c776a48888779d8e89d1961812fdd84541085a/lua/ak/config/editor/harpoon.lua#L100) functionality in my config I found another side effect of this issue.

1. Open a file
2. require("harpoon"):list:add()
3. Open another file
4. require("harpoon"):list:add()
5. Go to the first file
6. require("harpoon"):list:remove_at(1)

Open the UI: There are two items. The first item is empty. 

I would expect one item, and the second file on index 1.

I think [this part](https://github.com/ThePrimeagen/harpoon/blob/0378a6c428a0bed6a2781d459d7943843f374bce/lua/harpoon/list.lua#L212) might be the problem.

**Comment by abeldekat** [comment]
The `toggle` is working when using `replace_at`:

```lua
A.toggle = function()
  local list = H.get_current_list()
  local active_idx = H.find_active_idx(list)
  local len = #list.items
  if not active_idx or len == 0 then
    list:add()
  elseif active_idx == len then -- last item
    list:remove_at(active_idx) --
  else
    -- must replace with the last item in order to avoid gaps
    list:replace_at(active_idx, list.items[len])
  end
end
```

Unfortunately, I cannot submit a PR because I do not understand the purpose of methods `determine_length` and `guess_length`. As `list.items` is if of type `HarpoonItem[]`, why not use `table.insert` and `table.remove`?
