### ISSUE TITLE
nil value with lazy.nvim key setup

### ISSUE THREAD

**Issue by Archelyst** [ThePrimeagen/harpoon#561]
This is more of a support request. I have seen other people with this problem, but no solution, so I though it might be worth asking here, especially since you probably immediatedly know what's going wrong.

I'm trying to install harpoon2 with lazy like this:

```lua
return {
  "ThePrimeagen/harpoon",
  branch = "harpoon2",
  dependencies = { "nvim-lua/plenary.nvim" },
  keys = {
    {
      "<leader>h",
      function() require("harpoon"):list():add() end
    },
  }
}
```

When I press `<leader>h` I get this stracktrace:

```
E5108: Error executing lua: ~/.config/nvim/lua/plugins/harpoon2.lua:8: attempt to call method 'list' (a nil value)
stack traceback:
        ~/.config/nvim/lua/plugins/harpoon2.lua:8: in function <~/.config/nvim/lua/plugins/harpoon2.lua:8>
```

I printed out what `require()` returns, it's a table with `setup` and a few other things, but no `list` indeed`. I tried calling `setup()` before, same outcome.

What am I doing wrong here?

---

- OS: MacOS
- nvim: 0.9.5

**Comment by abeldekat** [comment]
Your config is correct.

For example, see [harpoon in LazyVim](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/harpoon2.lua)

Perhaps the old harpoon version is still present?
You could try to delete your `nvim` folders, and download from scratch. Then, check that the correct harpoon version is in `~/.local/share/nvim/lazy`.

On linux, I would remove everything with:

```lua
rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.cache/nvim
```

**Comment by Archelyst** [comment]
That was it! Thank you so much for taking your time to help me!

**Comment by abeldekat** [comment]
You're welcome!

**Comment by pedrohff** [comment]
@abeldekat your [setup](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/harpoon2.lua) could be documented in this repo, as in my point of view it's kind of shallow or misleading on how to use it properly with lazy.nvim. You helped me a lot, thanks!
