### ISSUE TITLE
Cusor position is not being saved on BufLeave

### ISSUE THREAD

**Issue by sug44** [ThePrimeagen/harpoon#566]
https://github.com/ThePrimeagen/harpoon/blob/da326d0438ac68dee9b6b62a734be940a8bd8405/lua/harpoon/list.lua#L229
On this line the list tries to get the index of an item that corresponds with the name. The `name` parameter comes from `vim.api.nvim_buf_get_name(bufnr)` which is always in form of an absolute path. So `index_of()` compares (almost always)relative path with absolute path always returning -1 and not saving the curson position in listItem.context

**Comment by ThePrimeagen** [comment]
you have a fix for this so i'll wait for this to be merged in that other pr

**Comment by ThePrimeagen** [comment]
i may have fixed this by forcing BufLeave to do the same set of operations as creating list items.  use normalize path

that way if it is absolute, it remains
if it is within, it will get relativeized.

lastly use a new value search function

**Comment by ThePrimeagen** [comment]
so i am going to close for now, if it continues to happen let me know
