### ISSUE TITLE
Quit vim, and the harpoon will lost.

### ISSUE THREAD

**Issue by Mr-LLLLL** [ThePrimeagen/harpoon#580]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------
my  config is:
``` lua
{
        "ThePrimeagen/harpoon",
        branch = "harpoon2",
        dependencies = { "nvim-lua/plenary.nvim" },
        event = "VeryLazy",
        config = function()
            local harpoon = require("harpoon")

            harpoon:setup({
                settings = {
                    save_on_toggle = true,
                    sync_on_ui_close = true,
                }
            })
        end
    }
```

when quit vim, the harpoon mark will be empty. I don't know this is feature or bug?
when i open vim. and add mark by harpoon:add(), it's work well. but, when i quit vim. and enter vim again. all mark before added will be miss.

when i quit vim, the ~/.local/share/nvim/harpoon/* files content have my marked information, but i enter vim. not load mark before added.

**Comment by Mr-LLLLL** [comment]
if quit vim, all mark will be lost. how can i save the mark i added?

**Comment by Mr-LLLLL** [comment]
same #577

**Comment by jueqingsizhe66** [comment]
Same problem!
