### ISSUE TITLE
Using line join <S-j> causes undefined behavior in harpoon menu. 

### ISSUE THREAD

**Issue by RamziA961** [ThePrimeagen/harpoon#597]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------

With the harpoon menu open, if line join is used, the two paths marked will we be joined on one line. This operation persists after saving harpoons state `:w`. Navigating to this path creates a new buffer out of the joined paths. Skill Issue?

Initial state:
<img width="927" alt="Screenshot 2024-05-18 at 21 02 00" src="https://github.com/ThePrimeagen/harpoon/assets/60425857/563112e5-c805-4122-a58c-40bfc7f3cc8d">

After a line join: `<S-j>`
<img width="927" alt="Screenshot 2024-05-18 at 21 02 15" src="https://github.com/ThePrimeagen/harpoon/assets/60425857/9e2d7608-8d6d-48ac-b925-d6f80cdd9a87">

Saved the buffer and reopened the menu, then navigated to the path in the image above. Notice the file path in the command area.
<img width="1473" alt="Screenshot 2024-05-18 at 21 03 10" src="https://github.com/ThePrimeagen/harpoon/assets/60425857/11203807-ba9d-4105-affe-baadbba65e17">

**Comment by maxrzaw** [comment]
This is the intended behavior. This way you can enter a file path and it will create a buffer for that file.

**Comment by RamziA961** [comment]
Oh that makes sense. Thanks for clearing that up
