### ISSUE TITLE
Harpoon Copies nvim tree file navigation

### ISSUE THREAD

**Issue by raghav-ai** [ThePrimeagen/harpoon#605]
**WARNING**
If this is about Harpoon1, the issue will be closed.  All support and everything of harpoon1 will be frozen on `master` until 4/20 or 6/9 and then harpoon2 will become master

Please use `harpoon2` for branch
---------------
I accidentally used the key bind on a Nvim tree and it copied the file tree. 
Not sure if it is intentional but can it only work on the code buffer.
![Screenshot 2024-06-04 at 2 41 57 PM](https://github.com/ThePrimeagen/harpoon/assets/67466406/91b50933-2603-431b-83ee-e62d66bcc6a6)

**Comment by rnwtn** [comment]
Hey, I don't see a builtin way to accomplish what you want, but you can use an autocmd to overwrite the keybinding for adding files to the harpoon list.

```lua
-- prevent adding the harpoon window to harpoon
vim.api.nvim_create_autocmd({ "FileType" }, {
  pattern = { "harpoon" }, -- Add any filetypes you want to exclude from being added
  callback = function()
    local opts = { buffer = true, noremap = true, silent = true }
    vim.keymap.set( "n", "<leader>a", "<NOP>", opts) -- change this to be the keymap you use to add files
  end,
})
```
