### ISSUE TITLE
Quick Menu Close

### ISSUE THREAD

**Issue by HarudaySharma** [ThePrimeagen/harpoon#609]
Is it possible that by pressing "Ctrl-c" the harpoon quick menu will get closed?.
It's just that I always close opened telescope windows using "C-c" and to go to normal mode in nvim. So it will be good if I could just use one keybinding to close all opened windows.

**Comment by K1ng-F1sher** [comment]
+1

**Comment by K1ng-F1sher** [comment]
I recently moved to harpoon2, which has the a `close_menu` function available from its API. You could check if the legacy version has a similar function as well.

**Comment by HarudaySharma** [comment]
@Lvdspek I'll check that. Thank You!!
