### ISSUE TITLE
[harpoon2] Change harpoon list on TabEnter & DirChanged events

### ISSUE THREAD

**Issue by BChausse-GoTo** [ThePrimeagen/harpoon#620]
**What issue are you having that you need harpoon to solve?**

Harpoon projects are set by vim's `pwd` from what I understand. However, neovim allows to have a different `pwd` per-tab
(see `:h tcd`). This is great when comparing multiple projects (ex: when rewriting a codebase in a new language). 

**However**, harpoon projects are set by the `pwd` encountered when harpoon launches so it never adapts to either tab changes or `:tcd`.

**Why doesn't the current config help?**

I don't see a way to easily change harpoons default list after startup.

**What proposed api changes are you suggesting?**

Allow for an external call that switches the current harpoon list/project. This way an autocmd could be configured (say with the `TabEnter` and `DirChanged` events to automatically reload harpoons list. This would allow true per-project harpoon lists.

**Comment by LehMichael** [comment]
I added a feature to reload on DirChanged in my harpoon extension: [harpoonEx](https://github.com/mike-jl/harpoonEx)
I also look at TabEnter, but right now there is now use, because internally the vim.loop.cwd() directory is used to differentiate between lists, and this directory is no changed if changing buffer.

**Comment by LehMichael** [comment]
Okay i was wrong. The dir does change, and even if it didn't, you can customize the way the key is generated. Right now you need to use :tcd to change the tab working directory. If the other tab has a different working directory, the DirChanged event is fired when switching tabs, so everything works as expected.
I don't know if there is a way to generate the key, where you get a per tab directory without using :tcd to explicitly set it, but if you need the reload on TabEnter, just let me know and I will implement it.
You can also always call harpoonEx:reset() manually when you want to trigger a reload.

**Comment by BChausse-GoTo** [comment]
@mike-jl You are a gentleman and a sholar!!!
This is absolutely fantastic! You are truly doing the Lord's work here :)
