### ISSUE TITLE
Harpoon2 and 'row_numberG' combination

### ISSUE THREAD

**Issue by reybits** [ThePrimeagen/harpoon#635]
Hello,
The plugin breaks the row_numberG command, which is used to navigate to a specific line in vim/nvim. When the plugin is disabled, the command works correctly again.

**Comment by ThePrimeagen** [comment]
I think this may be a you problem

Harpoon adds no remaps of any kind

**Comment by reybits** [comment]
Here is my config:

```lua
return {
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    config = function()
        local harpoon = require("harpoon")
        harpoon:setup()

        vim.keymap.set("n", "<leader>h", function()
            harpoon.ui:toggle_quick_menu(harpoon:list())
        end, { desc = "Open Harpoon window" })

        vim.keymap.set("n", "<leader>H", function()
            vim.notify("File '" .. vim.fn.expand("%") .. "' added to Harpoon", vim.log.levels.INFO)
            harpoon:list():add()
        end, { desc = "Add file to Harpoon" })

    end,
}
```

Looks like nothing specific to the problem.

**Comment by ThePrimeagen** [comment]
I'll relook through, but I am in extreme doubt here.

I do have some remaps but only on harpoon specific files

**Comment by reybits** [comment]
@ThePrimeagen Apologies for the incorrect bug report. The issue was on my end — your plugin is awesome!
