### ISSUE TITLE
dd won't delete a file from harpoon ui in a particular case

### ISSUE THREAD

**Issue by asuka-405** [ThePrimeagen/harpoon#641]
Bug - Using `dd` to delete an item sometimes won't work.
Env - telescope UI
Reproduce - delete any item from UI but instead of closing harpoon thru return key, use escape. In this case the list will persist whether you've delete a single item, or all 4.

**Comment by alexjjohnson91** [comment]
I am not sure this qualifies as a bug, instead just unimplemented functionality. 

If the UI is a buffer, ESC would not save the buffer, thus the item persists in the list. The ```<CR>``` saves the buffer, thus deleting the item from the list.

**Comment by asuka-405** [comment]
From a user perspective:
You delete items, press escape and expect it to clear buffer.
If something does not happen as expected, I'm sure it qualifies as a bug.

**Comment by pmeinhold** [comment]
I think this is a **feature**, not a bug.
ESC is not exactly the "save and continue" kind of key and, as a user, I expect it to let me *escape* without saving my changes. This behavior is actually useful if I made bad changes.

Plus, a normal Vim buffer does not automatically save your changes upon leaving either, does it? ;)

This also happens in the default Harpoon UI without Telescope btw. The issue should be closed imo.

**Comment by asuka-405** [comment]
That makes sense 😲

**Comment by mrogowski11** [comment]
What are the available methods to close the Harpoon window while preserving changes? The return key works, but it causes Vim to jump to whatever buffer was under the cursor in the Harpoon window. Harpoon's `list():select` and `toggle_quick_menu` discard the changes, as does Telescope's `actions.close`.

If I recall correctly, this behavior was introduced in Harpoon 2 and wasn't present in the first iteration.

**Comment by pmeinhold** [comment]
> What are the available methods to close the Harpoon window while preserving changes?

Not an expert on this, but for me `:w` just works, like I am saving a normal Vim buffer.
