### ISSUE TITLE
Clearing the cache for file options

### ISSUE THREAD

**Issue by PSPanesar** [ThePrimeagen/harpoon#67]
Hi
I have started to try out the extension. amazing idea.
some of the files listed on the menu and saved do not open but I can't remove them from he toggle menu or clear the cache. Is there a way to do that or delete the data?
thanks!

**Comment by ThePrimeagen** [comment]
I assume this means you figured it out?

**Comment by PSPanesar** [comment]
Yep I did, sorry :) I found the clearAll() function in the mark section which did the trick. Thanks for an awesome lib

**Comment by ThePrimeagen** [comment]
Tyty!

**Comment by Legazim** [comment]
For anyone in the future is clear_all() idk if it was changed
`lua require("harpoon.mark").clear_all()`
