### ISSUE TITLE
One Shot Commands.

### ISSUE THREAD

**Issue by ThePrimeagen** [ThePrimeagen/harpoon#71]
I would like to setup with harpoon one shot commands.

They would do the following.

1.  Use OneShotJobs from Plenary
2.  You can provide a transform to have the output abbreviated
3.  An option to have a small popup in the corner (you choose the corner) to display the abbreviated/full output
4.  Some sort of coloring/output/quick way to jump to full output along with the error (and message) / success status.
5.  History.  You can see the last X commands ran and their output.

**Comment by matu3ba** [comment]
Abbreviation of output requires custom filter, but neovim/lua ecosystem doesnt even have those for getting tests (ie jump to various tests and get the test name as library).
Take for example googletests, which only have vim plugins. Or tests themselfes, which are all written either for just a few languages or in vimscript.
I do assume you want oneshotjobs for mostly tests?

History requires program change context, but project-wide context is not tracked within undo files or neovim (yet).
