### ISSUE TITLE
Navigate on enter

### ISSUE THREAD

**Issue by danymat** [ThePrimeagen/harpoon#77]
I think commit a96cafc56dcebf2918dc43eab12126f6b5a76ac7 is broken (or maybe I'm excepting an other use case).

The use case I'm expecting with this commit is :
When I <CR>, I jump to the file specified.

What I get is:

![Capture d’écran 2021-05-11 à 17 40 58](https://user-images.githubusercontent.com/5306901/117844541-0c7cde00-b280-11eb-91a3-cf4aa4e110c9.png)

**Comment by ThePrimeagen** [comment]
I believe it works now.
