### ISSUE TITLE
Configurable terminal creation

### ISSUE THREAD

**Issue by jonathf** [ThePrimeagen/harpoon#85]
Much kudos to you for Harpoon! I have been l looking for a project like this a while now. I made a hackish version in pure vimscript a while back, but gave up on my implementation as it took too much of my time maintaining.

In my use case, I'd like to have terminals not only for the classical shell, but also to deal with REPLs. Think `gotoTerminal(1)` gives me normal Bash shell, `gotoTemrinal(2)` gives me Ipython (if in Python development).

In your current implementation, you would have to first create a shell `gotoTerminal(2)`, and then pass the next command with `sendCommand("ipython\n")`. This works, but feels awkwards:
1. The prompt does not go straight into the target app, and `$ ipython` will uneadely take up visual space.
2. Exiting now requires 2 steps, as first you close REPL, then close the shell.
3. Knowing if shell is Harpoons job, and you send `sendCommand("ipython\n")`, when it is already running, is an annoyance.

There are a few ways to solve this, but the approach I'd prefer is to add terminal create string as an extra optional arg. E.g. `gotoTerminal(2, ':e term://ipython -c \\%run %')` will, if terminal 2 does not exist, create Ipython REPL, execute the file you are editing, and terminate when done. If a REPL is already running, the argument is ignored.

Looking at your code, I should be able to add this. If you like, I can even give a try drafting it up.

**Comment by ThePrimeagen** [comment]
I do like this idea of having a repl. Perhaps something that is more permanent. You could also imagine that upon opening I would also like to see in some helper functions for the repl.

Great idea, if you would like to take a stab please go for it, else I will get to this soonish. I am on paternity leave which gives me more free time, but I also have a baby which takes all that free time away and replaces it with crying and poopy diapers.

**Comment by jonathf** [comment]
It is a tiny change, so no problem. Take a look at #86.
If you like to get at it another way, I an open for discussing it.

Congratulations, dude! They sleep a lot in the beginning, so if you are good at context switching while being sleep deprived, you will have lots of extra time. :)

Oh, and can I assume that you have the coconut oil handy for when you are changing diapers?

**Comment by jonathf** [comment]
So I have been told that my cultural references needs some updating.
In particular: https://www.urbandictionary.com/define.php?term=coconut%20oil
I wasn't aware of that particular connotation. And in light of it, my comment is... weird and problematic.

So if it wasn't clear: Oils, including coconut, are used together with dry-wipes during diaper changing. that is all.

This might perhaps be a new low for me on giving bad first impressions, but hey, you live and learn.

**Comment by ThePrimeagen** [comment]
I do want to revisit this. 

I am going to do a OSS / The Hoff kick off again for a couple weeks once I finish HPACK RFC :)

**Comment by jonathf** [comment]
Cool. Let me know if you want me to contribute.

**Comment by matu3ba** [comment]
The proposal is missing at least 2 pieces: 
1. Is the REPL read-only, ie only returns status after the initial command?
2. Is the REPL interactive, ie with some custom subcommands: https://github.com/ziglang/zig/issues/596 ie with manual send commands `update`,`run` etc ?

The first is a simple static string.
The latter is the users or plugins responsibility and requires to expose harpoon the state of the buffer (which can have nasty bugs on being asynchronous).
