### ISSUE TITLE
Feat: Add the ability to clear all terminals

### ISSUE THREAD

**Issue by joacohoyos** [ThePrimeagen/harpoon#91]
### Situation
 I'm using harpoon alongside with [git worktree](https://github.com/ThePrimeagen/git-worktree.nvim). 

When switching trees i always have to close the terminals I'm using to reopen them in the current directory.

### Feat
 It would be nice to have a function that let you kill all terminal, similar to the clear all marks feature.
 
 I don't mind trying to do it myself, but i don't know if it would be a good feature or not, maybe my case is very specific

**Comment by ThePrimeagen** [comment]
This is a great idea. I could try to do this tomorrow
