### ISSUE TITLE
Marks between directories

### ISSUE THREAD

**Issue by emr-arvig** [ThePrimeagen/harpoon#99]
I have harpoon configured like Prime's dotfiles

The menu is always a new menu between directories

Sometimes I want to swap between a file in my tools dir and my utils dir within a greater project and it's a new harpoon menu for each directory.

Something simple I am missing?

I tried defining an empty project spec in config but this does not work either
```
require("harpoon").setup({
    global_settings = {
        save_on_toggle = true,
        save_on_change = true,
    },
    projects = {
        ["absolute path to super cool project"] = {}
    }
})
```

**Comment by fritzlolpro** [comment]
Hi, got exactly same problem, after digging into code I found that projects is not about setting exact project, cuz there are lots of projects in runtime and every folder with mark counts as a project by default. 
![image](https://user-images.githubusercontent.com/10850158/142619761-14a6488a-682a-4d4d-ac1a-e664ccef3701.png)

I made a pull request to add the option you and me wanted -- having global marks.
Please take a look.

**Comment by rogueinkamp** [comment]
Awesome this looks like it was merged? GREAT news if so. Thanks for doing the work on this!

**Comment by fritzlolpro** [comment]
It wasn't merged, probably cuz my PR overlapsed with a huge code optimization + feature adding. 
I screwd up with upstream updating in my fork, so I made all changes anew, no PR yet, will make one soon.
I really love harpoon and think global marcks wouldnt harm
